### ISSUE TITLE
Decrease `ftl serve` startup and reconciliation time

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1010]
`ftl serve` uses the same timeouts as the production controller/runners, so under some circumstances it can easily take 5-10 seconds before the controller and runners come up. We should tune these timeouts so that it's basically instantaneous.

These timeouts are (almost?) all in [controller.go](https://github.com/TBD54566975/ftl/blob/main/backend/controller/controller.go).

**Comment by worstell** [comment]
related: #1381
