### ISSUE TITLE
Runners getting killed due to runner deployment directory clashes

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1045]
Steps to reproduce
- `ftl serve --recreate --log-level=DEBUG --idle-runners 3` (default idle runners also hits the issue)
- Wait for idle runners to be loaded, using deployment directories `[...]/ftl-runner/runner[0,1,2]/deployments`
- `ftl deploy examples/go/time -n 10`
- This will cause more runners to be spun up, using deployment directories `[...]/ftl-runner/runner[0,1,2...9]/deployments` (overlaps with above)
- As deployments are reconciled, there'll be errors of `error:runner2: Deployment terminated: signal: killed`, and the deployment count will increase, sometimes decrease, and eventually make its way to 10

**Comment by alecthomas** [comment]
[This line](https://github.com/TBD54566975/ftl/blob/aat%2Fconfig-overrides/backend/controller/scaling/localscaling/local_scaling.go#L87) should be using the randomly generated `config.Key`.
