### ISSUE TITLE
Run `autofmt` on `main` instead of PR

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1075]
When it's run on a PR, GitHub status reporting fails to work at all. I think what happens is that, the `autofmt` becomes the latest commit on the PR and status reporting switches to that commit, but because one action can't trigger another indirectly, the normal CI steps don't retrigger on the new commit, leaving them as zombies on the main PR commit.

**Comment by michaelneale** [comment]
https://github.com/TBD54566975/ftl/pull/1145 fixes this
