### ISSUE TITLE
Config panic when running `examples/go`

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#1085]
This panic:
```sh
ftl serve --recreate
info: Starting FTL with 1 controller(s)
info:controller0: Web console available at: http://localhost:8892
info:controller0: Deployed time-79874598af
info:controller0: Deployed echo-827798ce84
error:echo: panic in verb echo.echo: failed to get {echo default}: no such key "default": not found
```

I'm running serve in one terminal and then in another terminal:
```sh
ftl deploy examples/go --log-level=debug

... followed by

ftl call echo.echo
```

Not sure if this is an issue with my setup, but wanted to record what I saw here since I mentioned it before.

**Comment by alecthomas** [comment]
I can't replicate this:

```
🐚 ~/dev/ftl $ ftl deploy examples/go
info:time: Building module
info:echo: Building module
info:time: Deploying module
info:echo: Deploying module
🐚 ~/dev/ftl $ ftl call echo.echo
{"message":"Hello, anonymous!!! It is 2024-03-15 06:52:27.282601 +1100 AEDT!"}
```

Are you starting `ftl serve` from the FTL repo? If you don't, it won't pick up the location of the `ftl-project.toml` file.

**Comment by wesbillman** [comment]
Yeah, all the commands were running from the FTL repo.

I'm also not able to repro on main currently. Maybe something was up with my local setup at the time, but wanted to record the error just in case since I saw it a couple times. Hopefully, a nothingburger.

**Comment by alecthomas** [comment]
Ah, no it was a bug but it was fixed yesterday.

**Comment by alecthomas** [comment]
In #1079
