### ISSUE TITLE
Order and group FTL schema output in a nicer way

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1089]
Currently I think it's just alphabetical by (type, name):

```
module foo {
  config bar String

  config waz String

  data Data {}

  data Other {}

  database foo

  database waz

  secret secret String
  
  secret zap String

  verb myVerb(Data) Data
}
```

I think it would be nice if it was something more like:

```
module foo {
  config bar String
  config waz String
  secret secret String
  secret zap String

  database foo
  database waz

  data Data {}

  data Other {}

  verb myVerb(Data) Data
}
```

**Comment by worstell** [comment]
i like this! another thought- it might be nice to add an optional flag to `ftl schema get` for specifying modules, so you can scope your command in the case where you have a large schema and want to inspect specific module(s)

**Comment by alecthomas** [comment]
That would be super handy, I've wanted something like that many many times.

**Comment by alecthomas** [comment]
Create another issue for it?

**Comment by worstell** [comment]
> Create another issue for it?

added #1090
