### ISSUE TITLE
Unify error reporting functions

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1128]
I'm still seeing errors like this:

```
ftl: error: failed to build "module echo": failed to extract module schema: /Users/alec/dev/ftl/integration/testdata/go/httpingress/echo.go:160:1: ingress verb arrayData: request type builtin.HttpRequest<[ArrayType]>: 4:3: failed to monomorphise: /Users/alec/dev/ftl/integration/testdata/go/httpingress/echo.go:160:1: array element: /Users/alec/dev/ftl/integration/testdata/go/httpingress/echo.go:160:1: unknown type parameter "ArrayType"
```

I think the solution to this is to create a unified error type containing positional information, along with `Errorf` and `Wrapf` functions, that preserve a single error position. Basically identical to what is in the go-runtime, but shared, probably in `backend/schema`.

**Comment by wesbillman** [comment]
Is this covered by: https://github.com/TBD54566975/ftl/pull/1150

Here: https://github.com/TBD54566975/ftl/pull/1150/files#diff-35313b03e085394ebb55f42398129eb11d452c24d40cd233f98e755672b2a3a9R1

**Comment by alecthomas** [comment]
Yes!
