### ISSUE TITLE
Module updates not detected during initial deployment

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1161]
Steps:
- Start `ftl dev` with some modules
- While build and deploying modules, modify a module
- After initial modules are built and deployed, buildengine starts watching disk for updates
Once initial modules are built and deployed, we have a mismatch between the deployed modules and what is on disk, but the module is not built & deployed again.

I think this will be more important once ftl dev is happening within VS Code, and when working on many modules at once (like PFI)

**Comment by mistermoe** [comment]
I've actually been experiencing this a lot in a project with many modules. Strangely doesn't happen with just 1 module
