### ISSUE TITLE
Come up with a design for simple FTL visibility system

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1164]
Currently every verb has visibility of all others in the entire cluster, and the only visibility controls are whether a function is marked as ingress or not.

Some ideas to kick things off:

- Model it on programming languages? Public, protected, private, and package scoped vs. module scoped.
- Introduce the concept of groups of modules with a visibility boundary?

[Doc here](https://hackmd.io/ZnjimyM6SCe6aOzXMcFLig?view)

Issues:

- [x] #1324
- [x] #1354
- [x] #1376

**Comment by wesbillman** [comment]
Checklist complete :)
