### ISSUE TITLE
Push error span extraction down to the point where errors are created

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1165]
> While this is probably okay as a stop-gap, we should really be extending the error type to include range information so we can include it when the errors are created, as this is incredibly inefficient.

_Originally posted by @alecthomas in https://github.com/TBD54566975/ftl/pull/1163#discussion_r1550524860_

**Comment by wesbillman** [comment]
also tracked here: https://github.com/TBD54566975/ftl/issues/1158

**Comment by alecthomas** [comment]
Nice! Close this DUPE!
