### ISSUE TITLE
`runInBackground` should return errors

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1170]
Without doing this, it prints an error but then blocks for `--startup-timeout` before exiting with an error, rather than immediately exiting.

**Comment by deniseli** [comment]
@alecthomas could you recommend some steps to reproduce? I've tried running `ftl serve --background` in a second tab while there's another serve or dev running, and the failing `ftl serve --background` still finished quickly enough that I suspect I'm not understanding this issue correctly. Thanks :)

**Comment by alecthomas** [comment]
IIRC the function doesn't return errors, it logs them - it should return those errors.

**Comment by deniseli** [comment]
Got it, thanks!
