### ISSUE TITLE
Get rid of `all_{controllers,runners,ingress_routes}` from `GetStatus()`

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1171]
These won't scale.

**Comment by deniseli** [comment]
`waitForControllerOnline` in `cmd_serve.go` still retrieves the controller status via `GetStatus()`, so I'll leave the controller opt-in where it is to avoid breaking `ftl serve`. If there's a good workaround to avoid this and pull controller status out of `GetStatus()`, please let me know :)
