### ISSUE TITLE
Need a way to replace `just dev` to run other commands before `ftl dev .`

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#1179]
Currently, is some of the customer's repo we use `just` run commands before `ftl dev .`.

For example that just command might look something like this `just dev`:
```sh
# Start the FTL backend in "dev mode".
dev:
  # Restart when any migrations change.
  watchexec -r -f '**/migrations/*.sql' 'just db-migrate-all && ftl dev backend/modules --recreate'
```

This will run db migrations before starting ftl dev and rerun both if anything changes.

**Comment by alecthomas** [comment]
My initial thoughts are that these should go in `ftl-project.toml` rather than `ftl.toml`, but I'm not 100% sure. We could start with something super simple though, that just executes a command before building.

**Comment by matt2e** [comment]
@wesbillman with your example, i wonder if we end up with this issue:
- someone runs dev with some args
- the config says to do something like you mention above that watches and then kicks off dev again
- At some point the person is wondering why dev isnt running with the args they inputed (the pre-run script restarted dev with different args)

**Comment by wesbillman** [comment]
Oh yeah! My example might be bad since I just copy pasted, but I agree that having a `watchexec` type command in the rebuild would be pretty wild to debug.

I think a more common case might be something like
```toml
[commands]
pre-build = "just db-migrate-all"
```
