### ISSUE TITLE
`ftl dev` randomly hangs

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/ftl#1201]
I'm not sure how to reproduce this one consistently but it happens frequently. project i'm working in has 2 modules

https://github.com/TBD54566975/ftl/assets/4887440/29e6b8b4-8d8f-41c6-a6ec-fee17479c9f4

**Comment by wesbillman** [comment]
Having trouble reproducing this one. If I add/remove the log files it seems to consistently reload as expected. 🤔

**Comment by matt2e** [comment]
I think I saw this once or twice but it was when I was neck deep in other changes in this area so I'd blamed my half finished code. I'll have a go at repro-ing as well

**Comment by matt2e** [comment]
Will look into why this is happening

**Comment by alecthomas** [comment]
Looks like you're running at `debug`, you should probably run at `trace` to get more information.

**Comment by matt2e** [comment]
Above is a false alarm sorry, looks like it was working as correctly.
When a few changes for a module get queued up, the queue builds the latest it finds on disk, and then subsequent builds find no changes which is why we get the log "Deployment already exists" and no info log saying "deployed module". Subsequent changes do make it up.
So what I repro'd is different than what @mistermoe saw.
Still trying to repro

**Comment by alecthomas** [comment]
Ah right. That is another bug though - it should exclude repeated builds of the same module. Something like "if the build is more recent than the timestamp of the event, do nothing".

**Comment by matt2e** [comment]
Wasn't able to repro this issue. Anyone else want to have a try?
Moe's steps leading up to this issue while working on the ledger module:
> I created a module rates
> ran just dev which led to an infinite build loop
> killed ^ and restarted. Things worked fine
> added a single verb to rates purely for the sake of calling it from ledger module
> Moved back over to implement ftl.Call in ledger module. Finished and hit save
> infinite build loop started again. No errors in code
> killed and restarted just dev
> Made one adjustment to add a log statement
> Ran my curl request didn’t see the log I excepted then realized that just dev wasn’t rebuilding

**Comment by matt2e** [comment]
Other issue found has been moved here: https://github.com/TBD54566975/ftl/issues/1210

**Comment by wesbillman** [comment]
Hey @mistermoe!! I haven't seen this in a while. Are you seeing this with the current versions? I have a feeling it was resolved with some of the other engine stuff, but want to confirm that's true with you :)

**Comment by mistermoe** [comment]
agreed @wesbillman ! going to close this out and re-open if i run into it agane
