### ISSUE TITLE
Kotlin modules get renamed to "builtin" during deployment

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1213]
Run `ftl dev examples/kotlin/time --recreate --log-level=DEBUG`
By the end, a deployment will be created called "builtin-xxxxxx" instead of "time-xxxxxxx"

**Comment by matt2e** [comment]
From what i can tell, when reading the module schema from the pb file, the name is `builtin` instead of `time`.
Adding these lines to `ExtractSchemeRule.kt` at line 172 seems to fix the issue, but I don't understand why.
```
if (moduleName == "builtin") {
      throw IllegalArgumentException("Why does this fix it?")
    }
```

**Comment by wesbillman** [comment]
I'm getting this when running tests locally now as well.
```sh
[ERROR] Failed to execute goal com.github.ozsie:detekt-maven-plugin:1.23.5:check-with-type-resolution (default) on project echo: Execution default of goal com.github.ozsie:detekt-maven-plugin:1.23.5:check-with-type-resolution failed: Analyzing /Users/wesbillman/dev/ftl/buildengine/testdata/projects/echokotlin/target/generated-sources/ftl/builtin/Builtin.kt led to an exception.
[ERROR] Location: xyz.block.ftl.schemaextractor.ExtractSchemaRule.postVisit(ExtractSchemaRule.kt:177)
[ERROR] The original exception message was: Why does this fix it?
```

**Comment by alecthomas** [comment]
Same fix for me, I think it's just yet another weird Maven cache thing 🤷‍♂️
