### ISSUE TITLE
Replace ad-hoc envar "protocol" with something more structured

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1240]
Currently we utilise a random set of environment variables such as `FTL_CONFIG`, `FTL_ENDPOINT`, `LOG_LEVEL`, etc. to propagate configuration state between the runner and the module it is executing. We should come up with something less gross.

One option would be to double down on using envars for this, but have a data structure that encapsulates it all. Another option would be to push some of this back to the Runner over gRPC. That is to read a config key or secret key, the user code calls a gRPC method on the Runner.

**Comment by alecthomas** [comment]
Just adding triage back to this one because someone needs to take this, so we should discuss next week.

**Comment by alecthomas** [comment]
Stupid bot.

**Comment by matt2e** [comment]
- design doc
- have a single get into ftl from user code that returns structured data for all of this

**Comment by matt2e** [comment]
Doc: https://hackmd.io/@ftl/SyynEK2eC

**Comment by wesbillman** [comment]
@matt2e is this issue related to this work here? Or something else https://github.com/TBD54566975/ftl/issues/919

**Comment by alecthomas** [comment]
That one is more related to pulling config/secrets from different sources in production - ie. a DB table for config, and AWS Secrets Manager for secrets. The plumbing is there in the config resolvers, we just need implementations for them.
