### ISSUE TITLE
Support sum types in the type system

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1248]
- [x] #1375
- [x] #1262 
- [x] #1247
- [x] #1386
- [x] #1387
- [x] #1388
- [x] #1451 
- [x] #1449

[Design](https://hackmd.io/TZqMfuyHTYaXd1gSECbpFg)

There are a few reasons to support sum types in FTL, but one of the primary motivations is mapping FTL types to JSON. JSON very frequently supports multiple types for a single key. eg. both of these might be valid keys:

```json
{
  "depends": "foo"
}
```

and

```json
{
  "depends": ["foo", "bar"]
}
```

We'll need to ensure that however we implement this, it's relatively simple to express sum types in each language, even languages like Go and Kotlin that don't provide first-class support for sum types.

eg. in Go this might look like:

```go
//ftl:sumtype
type ScalarOrList interface { scalarOrList() }

type Scalar string
func (Scalar) scalarOrList() {}

type List []string
func (Scalar) scalarOrList() {}

type Response struct {
  Depends ScalarOrList `json:"depends"`
}
```

**Comment by alecthomas** [comment]
How are sum types represented in ingress JSON? `{"kind": "Scalar"}`?

**Comment by worstell** [comment]
> How are sum types represented in ingress JSON? `{"kind": "Scalar", "value": "foo"}`? In the example above this is probably redundant because we can tell from the type, but for data structures we wouldn't be able to. Though it might still be ambiguous in the case of eg. `Bytes | String` because `Bytes` is represented as a string, so probably better to be explicit.

yeah a lot to unpack here, updated the design with discussion around encoding/a proposed strategy

**Comment by alecthomas** [comment]
Yay!
