### ISSUE TITLE
Add additional events for cron jobs

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1260]
Events like:
"could not build body for cron job"
"Could not kill stale cron job %q because schedule could not be parsed: %q"

> all of these log messages should be associated with the cron job in the events table so that the user can filter and find issues with their cron jobs.

**Comment by matt2e** [comment]
This may end up being rolled into async calls work

**Comment by safeer** [comment]
Cron is rewritten to use async_calls, so this is a dupe of #2473
