### ISSUE TITLE
Write a completely custom JSON decoder/encoder

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1262]
Currently we delegate to the `encoding/json` package under certain circumstances, which can do the wrong thing. We should also add support for `,omitempty` including for any zero value (not just nil, as with the stdlib).

**Comment by deniseli** [comment]
The work left to do on this ticket is the remaining `omitempty` support for `encodeValue()`.

**Comment by alecthomas** [comment]
I can't recall if this was specifically referring to ingress, or to the backend encoder, or both, but it feels like we could/should use it for both.

**Comment by deniseli** [comment]
Now that we've taken out the json marshaler logic in the custom encoder, we are _nearly_ doing that already. That said, referring back to the title, the fact that we're still using `json.Decoder` means we don't _really_ have a "completely custom JSON decoder/encoder". I added https://github.com/TBD54566975/ftl/issues/1432 to track the idea of replacing `json.Decoder` with a better, custom implementation. So I _think_ we can close this issue after the `omitempty` handling is done (which I'm working on now)... but please let me know if we missed anything

**Comment by alecthomas** [comment]
I think I got a bit mixed up before - we should separate the two concerns. The ingress JSON encoding/decoding shouldn't be tightly coupled to the backend `encoding` package. I think we'll want completely separate encoders/decoders for both.

**Comment by deniseli** [comment]
Ahhh got it, thanks for clarifying! I'll make a note to touch base with Lizzy on this when she's back. In the meantime, I did a quick review of https://github.com/TBD54566975/ftl/issues/1432 and that doesn't talk about where the encoder is used, except that it's defined in go-runtime, so I think we're ok. Please let me know if I missed something, though - there were a lot of loose ends on this one

**Comment by deniseli** [comment]
I also just added https://github.com/TBD54566975/ftl/issues/1439 to track the removal of `json.RawMessage` so that we can remove the special case. So I believe all the outstanding work related to this ticket is now tracked between https://github.com/TBD54566975/ftl/issues/1439 and https://github.com/TBD54566975/ftl/issues/1432.
