### ISSUE TITLE
Add `ftl upgrade` command to manage min FTL versions across `ftl-project.toml`, `go.mod`, and `pom.xml`

### ISSUE THREAD

**Issue by deniseli** [TBD54566975/ftl#1263]
Context: comments in PR https://github.com/TBD54566975/ftl/pull/1244

**Comment by deniseli** [comment]
`go.mod` [specifies](https://go.dev/ref/mod#go-mod-file-require ) _minimum_ versions in the `require` directive, but `pom.xml` [sets target version](https://maven.apache.org/pom.html), so these do behave slightly differently. However, using the minimum version _as_ the target version seems like reasonable behavior. A bit more thought/discussion would be good to confirm.

**Comment by alecthomas** [comment]
Closing this out in favour of a generalised "settings" command.
