### ISSUE TITLE
Discuss: ftl.Config and ftl.Secret could be declared with non-FTL types

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1293]
Currently when defining config and secrets, only ftl types are allowed. eg:
```go
var complexSecret = ftl.Secret[map[string]any]("custom_secret")
```
Every time they declare things like this, they'll also need to add a helper function which reads this generally typed value and parses it into their custom type (eg: `CustomSecretType`)

We should discuss if we want to allow this:
```go
var complexSecret = ftl.Secret[CustomSecretType]("custom_secret")
```
When called within the module, it would return the custom struct.
Everywhere else it will be returned as `map[string]any`

**Comment by alecthomas** [comment]
Hey @matt2e I forgot you were writing this up, but I created #1296 with more detail so I'll close this one. Apologies!
