### ISSUE TITLE
Is there a way to specify which project toml to use in tests?

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/ftl#1309]
```go
secHandle := ftl.Secret[string]("some_secret").Get(ctx)
```

seems to read `ftl-project.toml` regardless of me setting the `FTL_CONFIG` environment variable

**Comment by alecthomas** [comment]
Work @matt2e is doing will solve this soon

**Comment by matt2e** [comment]
@mistermoe I've been going down the path of making tests explicitly declare configs/secrets/DSNs (example code here: https://github.com/TBD54566975/ftl/pull/1311 )
Is there anything in your use case that wouldn't fit into that pattern?

**Comment by matt2e** [comment]
Solved in this PR: https://github.com/TBD54566975/ftl/pull/1411
Example:
```
ctx := ftltest.Context(
  ftltest.WithProjectFile("path/to/ftl-project.toml"),
  ...
)
```
