### ISSUE TITLE
[Suggestion] rename `ftl.Map`

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/ftl#1346]
> [!NOTE]
> Feel free to close this issue if y'all think otherwise! no hard feelings whatsoever. Just something that crossed my mind when i initially came across the function when looking for `ftl.Singleton`: 

`ftl.Map` feels a wee bit ambiguous. i think folks would instinctively think of a `map[string]any` sort of map prior to thinking: _"Map this resource to this function"._

If someone did go as far as hovering over `Map` to read the godoc, it sort of makes it sound like you're using `Map` to create a _binding_ between a resource and a function so that _anywhere_ the resource is fetched, that function would execute instead. Maybe `ftl.Use` or `ftl.UseResource` would be more clear.

<img width="1182" alt="image" src="https://github.com/TBD54566975/ftl/assets/4887440/3867c186-e06e-42e7-95dc-2a0ea240a427">

**Comment by alecthomas** [comment]
I think most programmers today are familiar with the concept of "map" as a higher order function, so I think the name is fine. Also the signature makes it very clear it's not related to a map data structure. If anything I think like `Use` is more confusing, to me personally at least?

Maybe the docs could change to reflect its purpose better though? But another option might be making it a method on the `Handle` interface, though that means that every resource type would have to implement that method, which would be annoying.
