### ISSUE TITLE
Stop ftl admin erasing requests every time you leave tab

### ISSUE THREAD

**Issue by corcillo** [TBD54566975/ftl#1430]
On ftl admin panels, when you fill out the contents of the request json, if you leave tab for a second it refreshes the contents back to the original Latin 😭
Really hard when i have to leave the screen to look up a previous request or bank account number in another tab.

**Comment by wesbillman** [comment]
Fixed with #1433

A future feature might also include a way to save and manage multiple recents per verb, but for now, this PR will remember the text across tabs and verbs.
