### ISSUE TITLE
fix transitive export visibility in go schema parser

### ISSUE THREAD

**Issue by worstell** [TBD54566975/ftl#1449]
during schema extraction we add the first data decl we come across in the AST traversal to the module schema. if the same type gets visited transitively later on, we don't update the export visibility if changed. this can result in transitively exported things not appearing in the module stubs

same problem for enums

**Comment by alecthomas** [comment]
We couldn't quite figure out how to replicate this @worstell, so assigning to but if you to add reproduction notes (or fix if that's easier).
