### ISSUE TITLE
ensure `main.go` is updated with schema changes during `ftl dev`

### ISSUE THREAD

**Issue by worstell** [TBD54566975/ftl#1451]
it seemed like the build dir `main.go` wasn't updating on redeploys until quitting and rerunning with `ftl dev --recreate`. we need to recompile this file whenever we rebuild the schema because it generates based on schema information now

**Comment by wesbillman** [comment]
@safeer I assigned this one to you since it's in the same area as the code you're looking at to delete the `DeployDir` during the build phase.

**Comment by alecthomas** [comment]
Delete the `DeployDir` or the build dir? If it's the former, @gak implemented garbage collection of it yesterday. But the latter makes sense.

**Comment by safeer** [comment]
@alecthomas is the generated `_ftl` directory the `DeployDir` or the build directory? I have a PR up, but I was mistakenly under the impression they were the same 🙃

**Comment by alecthomas** [comment]
I was thinking of [DeploymentDir](https://github.com/TBD54566975/ftl/blob/main/backend/runner/runner.go#L47), but I think it's cunningly called `DeployDir` in the context of the build system 😂 - so `DeployDir` is correct yep, I was just clarifying.

**Comment by safeer** [comment]
Fixed by #1500; verified that `main.go` is updated now on schema changes.
