### ISSUE TITLE
Improve error messaging when types are not exported

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#1456]
When a user tries to `ftl.call` a verb that is not exported, it isn't obvious to the user what they need to do to resolve the error. Should we add a message like 

Currently the message(s) are:
> call first argument must be a function but is an unresolved reference to time.Internal
> call first argument must be a function in an ftl module

Should we update to something like:
> call first argument must be a function but is an unresolved reference to time.Internalftl, does is need to be exported?
> call first argument must be a function in an ftl module, does it need to be exported?

![Screenshot 2024-05-09 at 2 43 43 PM](https://github.com/TBD54566975/ftl/assets/51647/41fbcc64-c2e6-44d5-a10f-a279b48c53cf)

```go
//ftl:verb
func Internal(ctx context.Context, req TimeRequest) (TimeResponse, error) {
	return TimeResponse{Time: time.Now()}, nil
}
```

**Comment by jonathanj-square** [comment]
covered by https://github.com/jonathanj-square
