### ISSUE TITLE
Default to panicking if a test accesses a real db

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1460]
We now have `ftltest.WithDatabase(...)` which switches the DSN to a `<name>_test` db (and wipes the db tables).
It can be hard to tell when writing tests if a real db is accidentally being used.
example: I'm trying to move pfi tests to use test dbs but it's pretty opaque without looking through each package carefully.

If there is a legitimate usecase for touching db's that havent been swapped with `ftltest.WithDatabase` we could add a option to allow it?

Thoughts?

**Comment by alecthomas** [comment]
How would we do this?

**Comment by matt2e** [comment]
- `ftltest.WithDatabase(...)` could mark the `ModuleContext.Database` as a test db.
- module context already knows if it is in a test context from ftltest
- So in `modulecontext.GetDatabase(name)`, we can check for the case of `moduleCtx.isTest && !database.isTestDB`

**Comment by alecthomas** [comment]
Sounds like a good idea to me.
