### ISSUE TITLE
Integration tests use the system `ftl` instead of the local `dev` version

### ISSUE THREAD

**Issue by deniseli** [TBD54566975/ftl#1481]
If your integration tests depend on using a more recent FTL release than your homebrew installed version, then your tests will fail. Temporary workaround if you need the latest release is to `brew upgrade ftl` in your system, but we should fix this by having having the integration tests always use your local `dev` version.

**Comment by alecthomas** [comment]
This is not quite correct. The integration tests use whatever is in the `$PATH`, which will be the local development version of FTL if the Hermit environment is activated. What I suspect is happening in your case is that you're running the tests from inside VSCode, which doesn't preserve Hermit's `$PATH` under some circumstances.

**Comment by deniseli** [comment]
Ahhhhh that makes sense. Thanks!!
