### ISSUE TITLE
type can only be part of one type enum, second is silently ignored

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1492]
Steps:
- define a type enum
- define a second type enum
- define a type that conforms to both
- Expected, it is a case in both.

Use case:
- I can imagine wanting to define a `User` type and a `Group` type, and have them both conform to `Owner` and `Beneficiary` or something.

```go
//ftl:enum
type EnumType interface{ enumType() }

//ftl:enum
type EnumType2 interface{ enumType2() }

type Example string

func (Example) enumType()  {}
func (Example) enumType2() {}
```

Current we end up with:
```
enum EnumType {
    Example String
}

enum EnumType2 {
}
```
With nothing no errors

**Comment by alecthomas** [comment]
I don't know if this would be possible to support in other languages. Typically each variant is unique to its containing sum type.

**Comment by matt2e** [comment]
I'll make it an error for now then and we can revisit later if we want.
