### ISSUE TITLE
What is the expected behavior of `ftl secret set --op --json` ?

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/ftl#1494]
per a discussion in a prior issue: https://github.com/TBD54566975/ftl/issues/1295#issuecomment-2081223143

> Actually thinking about it a bit more now, it may make more sense to store everything related to a given vendor in a single secret that is a json object. thinking back to using AWS Secrets Manager and that's actually how it's done: [reference](https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_secret_json_structure.html) in which case `Map` as it is works totally fine.

I was hoping to move to ^ approach for secrets in our project. for local development our secrets are stored in 1password. A given secret in 1password would be set up like so:

![image](https://github.com/TBD54566975/ftl/assets/4887440/a039896c-58bd-4d62-a5f3-52071eb6c6e6)

attempting to add the secret to ftl led to the following:

```
❯ echo -n op://json-test/secret | ftl secret set json_test --op --json
ftl: error: secret is not valid JSON: invalid character 'o' looking for beginning of value
```

TBH, ^ was 50% expected as the `--json` flag when used with the `--inline` provider is expecting that actual secret provided to be json. with `--op` however (and i suppose `--keychain` as well) there's 1 additional level of indirection. 

What i'm hoping to be able to do is something like the following and have it work regardless of the underlying secret provider thats being used (aws secrets manager in prod, op or keychain locally etc.):

```go
package adminbff

import (
	"context"
	"fmt"

	"github.com/TBD54566975/ftl/go-runtime/ftl" // Import the FTL SDK.
)

type RandoVendorSecret struct {
	Hi string
}

type RandoVendorClient struct {
	ApiKey string
}

func (c *RandoVendorClient) doSomething() {}

var randoVendorClient = ftl.Map(ftl.Secret[RandoVendorSecret]("json_test"), func(ctx context.Context, sec RandoVendorSecret) (RandoVendorClient, error) {
	fmt.Println(sec)

	return RandoVendorClient{ApiKey: sec.Hi}, nil
})

type EchoRequest struct {
	Name ftl.Option[string] `json:"name"`
}

type EchoResponse struct {
	Message string `json:"message"`
}

//ftl:verb
func Echo(ctx context.Context, req EchoRequest) (EchoResponse, error) {
	client := randoVendorClient.Get(ctx)
	client.doSomething()
	return EchoResponse{Message: fmt.Sprintf("Hello, %s!", req.Name.Default("anonymous"))}, nil
}
```

Strongly typing the secret as described here: https://github.com/TBD54566975/ftl/issues/1295#issuecomment-2081231861 would be awesome

**Comment by alecthomas** [comment]
I think if you just put JSON into 1Password it should work, at least that is the idea. Have you tried that?

**Comment by alecthomas** [comment]
Oh haha I didn't see the screenshot 😂

**Comment by alecthomas** [comment]
Closing in favour of #1498 which defines a solution
