### ISSUE TITLE
Extend 1Password secret provider to return the entire entry as JSON

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1498]
Currently a single field must be specified as `op://<vault>/<entry>/<field>`, which is always treated as a single JSON string.

But sometimes we want a composite value. A proposal @mistermoe and I came up with is that if the reference is to the entry itself, eg. `op://<vault>/<entry>`, FTL would retrieve all fields as a JSON object.

eg. Given the following entry as JSON:

```json
{
  "id": "xyz",
  "title": "JSON",
  "tags": ["json"],
  "version": 2,
  "vault": {
    "id": "xyz",
    "name": "Personal"
  },
  "category": "LOGIN",
  "last_edited_by": "xyz",
  "created_at": "2024-05-15T19:12:04Z",
  "updated_at": "2024-05-15T19:19:54Z",
  "additional_information": "test",
  "fields": [
    {
      "id": "password",
      "type": "CONCEALED",
      "purpose": "PASSWORD",
      "label": "password",
      "value": "aSecretPassword",
      "reference": "op://Personal/JSON/password",
      "password_details": {
        "strength": "VERY_GOOD"
      }
    },
    {
      "id": "username",
      "type": "STRING",
      "purpose": "USERNAME",
      "label": "username",
      "value": "test",
      "reference": "op://Personal/JSON/username"
    },
    {
      "id": "notesPlain",
      "type": "STRING",
      "purpose": "NOTES",
      "label": "notesPlain",
      "reference": "op://Personal/JSON/notesPlain"
    }
  ]
}
```

If the secret reference was `op://Personal/JSON/password` we would return the JSON string quoted value `"aSecretPassword"`.

If the secret reference was `op://Personal/JSON` we would retrieve the JSON object `{"password": "aSecretPassword", "username": "test"}`. Note that `notesPlain` would be omitted because it has no value.

Unfortunately we'll need to manually parse the `op://` reference in order to pass the individual values to `op item get --json`, because it doesn't support `op://` references directly. We'll then need to unmarshal the JSON into an intermediate structure in order to retrieve the fields.

**Comment by alecthomas** [comment]
This will resolve #1494

**Comment by mistermoe** [comment]
@gak thank you!

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExc24xNzN5Nm1jZDY0eWl0dWx6MXF6NWVwZDFpNm44eXh6aWh3cWRqYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/PPe3uQDMaxAti/giphy.gif)
