### ISSUE TITLE
Allow module tests to be run from VS Code

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1502]
We are close to having module unit tests work within VS Code. This will also make it easy to debug module code/tests.
The only thing missing is that `ftltest.WithProjectFiles()` relies on `FTL_CONFIG` envar.

Workarounds:
- Set the variable in hermit, open vscode with `code .`
- Set it up as an envar in VS Code's settings json
Both of these are annoying because you have to make sure you don't commit the changes because the path includes your home directory.

Possible solution:
We switch logic to look for expected file names in the current folder, if missing go up a level ... repeat.
This is similar to how you can call `just` from anywhere within the directory structure
We could make FTL_CONFIG and ftltest.WithProjectFiles(...) do this. This would make passing in strings to the test function actually usable in more cases, and the ftl config value to be able to be commited to git

**Comment by matt2e** [comment]
from discussion with @mistermoe

**Comment by alecthomas** [comment]
The current logic when running `ftl dev` is [here](https://github.com/TBD54566975/ftl/blob/main/common/projectconfig/projectconfig.go#L53). We should probably replicate that.

- If a config is passed via either the CLI or envar use them.
- Otherwise use `internal.GitRoot() + "/ftl-project.toml" if it exists.

**Comment by alecthomas** [comment]
In fact we should probably use `ConfigPaths()` directly...

**Comment by matt2e** [comment]
good first issue?
