### ISSUE TITLE
no error when type enum is an interface without a function

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1527]
Steps to repro:
- Define an ftl type enum, but with an empty interface

Expected:
- This should be an error on the enum, and not product errors everywhere else

What actually happens:
- Errors appear every else because *everything* is now an enum variant because it conforms to the interface

```go
//ftl:enum
type OpenEnum interface{}

// innocent bystander
type DAL struct {
  db *sql.DB
}
```
error:
> unsupported type "*database/sql.DB" for field "db"

**Comment by alecthomas** [comment]
😂

**Comment by worstell** [comment]
we should also validate that the interface function is unexported, i don't think we're doing that right now
