### ISSUE TITLE
Figure out a protocol for FTL to interact with a language runtime/build

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#153]
Previously there was the `ftl-runtime-<lang>` executable, but the goal was to replace that with implementations of `RunnerService` such that local development looked like any other runner. We need to figure out how that will work in each language.

**Comment by alecthomas** [comment]
After a bit of experience with Kotlin and Go, I think this will be a language specific solution. In Kotlin, for example, a Gradle plugin does all the heavy lifting. In Go there will need to be a tool, because Go doesn't have an extensible build system.

**Comment by wesbillman** [comment]
The FTL toml file is currently our solution to this. It includes the artifacts and language.
