### ISSUE TITLE
should `ftl secret set` create a project toml if one is specified that doesn't exist?

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/ftl#1561]
Slightly similar to #1338 but different in the sense that i'm specifying a toml file that isn't the default project toml e.g.

```bash
❯ echo -n "hi" | ftl secret set -C ftl-project-idk.toml --inline yo
ftl: error: open ftl-project-idk.toml: no such file or directory
```

instinctively i feel like the command should create the toml if it doesn't already exist but will leave that up to y'all to decide! maybe there's a good reason not to do this or there's another pre-existing command that should be used to create toml config files.

**Comment by mistermoe** [comment]
lol whoa @ftl-robot can see into the future

![image](https://github.com/TBD54566975/ftl/assets/4887440/b161ad41-8894-49f6-a167-bf7ce9210b52)

**Comment by alecthomas** [comment]
Agreed Moe

**Comment by alecthomas** [comment]
> lol whoa @ftl-robot can see into the future

Makes you wonder about the fidelity of GitHub hey?
