### ISSUE TITLE
Can we remove the `/ingress` from the path from http ingress request

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#1609]
For local development when coding against pre defined specifications, this can make things a bit more difficult.

Also, would it be stripped when running in a production environment?

**Comment by alecthomas** [comment]
We're currently hosting the gRPC servers and the ingress on the same port, so we can't host them on `/`. That said, it's probably safer and cleaner to just put ingress on a separate port and HTTP server, which would solve this problem as well.

**Comment by wesbillman** [comment]
Oh nice yea! that might help with some of the security controls as well so they could have different roles for the ingress port vs. others
