### ISSUE TITLE
When a new module is created the console view of that module does not get refreshed

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#163]
Reproduction:

```
ftl initdb --recreate
ftl-dev
```

Open console in browser.

```
ftl go deploy -S $PWD -d ./examples/time
```

Go back to console and "time" should be visible. Click time and you will end up in an empty view.

**Comment by wesbillman** [comment]
This should probably be updated to use `useContext(schemaContext)` instead: https://github.com/TBD54566975/ftl/blob/main/console/client/src/features/modules/ModulePage.tsx#L11-L12.

Here's an example: https://github.com/TBD54566975/ftl/blob/main/console/client/src/features/verbs/VerbPage.tsx#L14C7-L16

Also, we might want to think about removing this provider to avoid this issue in the future: https://github.com/TBD54566975/ftl/blob/main/console/client/src/providers/modules-provider.tsx
