### ISSUE TITLE
PubSub error positions are incorrect

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1634]
<img width="1756" alt="image" src="https://github.com/TBD54566975/ftl/assets/41767/90c0b7ec-6cb3-46ed-b44d-44f8eb20c472">

**Comment by wesbillman** [comment]
![Screenshot 2024-06-12 at 11 56 14 AM](https://github.com/TBD54566975/ftl/assets/51647/af87ff86-ab77-4193-9bd2-67e94d190fff)

I think this was resolved with recent schema error and lsp fixes.
