### ISSUE TITLE
ftl-project.toml should be generated if doesn't exist when running `ftl init`

### ISSUE THREAD

**Issue by gak** [TBD54566975/ftl#1639]

**Comment by deniseli** [comment]
I can grab this since I'm already working on https://github.com/TBD54566975/ftl/issues/1561

**Comment by alecthomas** [comment]
IIRC the reason for this was so the VSCode extension would detect an FTL project, though strangely I do not have this issue in a new project I create.

**Comment by alecthomas** [comment]
Aaah, because it looks for `ftl` in `bin/ftl` I think @wesbillman ? What are the heuristics it uses?

Regardless, I think creating an `ftl-project.toml` in the Git root is a very good idea.
