### ISSUE TITLE
Unable to run ftl with multiple controllers

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1643]
Tried this command: `ftl dev --recreate --log-level=DEBUG --controllers=5`
Got the following output each time:

> debug: Unary RPC failed: unavailable: dial tcp [::1]:8892: connect: connection refused: /xyz.block.ftl.v1.ControllerService/Ping
> debug: Unary RPC failed: unavailable: dial tcp [::1]:8892: connect: connection refused: /xyz.block.ftl.v1.ControllerService/Ping
> info: Starting FTL with 5 controller(s)
> debug: Reusing existing docker container ftl-db-1 on port 54320 for postgres db
> debug: Waiting for ftl-db-1 to be healthy
> debug: Postgres DSN: postgres://postgres:secret@localhost:54320/ftl?sslmode=disable
> debug:migrate: Applying: 001_init.sql
> debug:controller0: Starting FTL controller
> debug:controller0: Building console...
> debug:controller2: Starting FTL controller
> debug:controller2: Building console...
> debug:controller4: Starting FTL controller
> debug:controller4: Building console...
> debug:controller3: Starting FTL controller
> debug:controller3: Building console...
> debug:controller1: Starting FTL controller
> debug:controller1: Building console...
> debug: Unary RPC failed: unavailable: dial tcp [::1]:8892: connect: connection refused: /xyz.block.ftl.v1.ControllerService/Status
> info:controller2: Web console available at: http://localhost:8894
> info:controller1: Web console available at: http://localhost:8893
> info:controller4: Web console available at: http://localhost:8896
> info:controller3: Web console available at: http://localhost:8895
> info:controller0: Web console available at: http://localhost:8892
> debug:controller1: Starting DB listener
> debug:controller2: Starting DB listener
> debug:controller1: Listening on http://localhost:8893
> debug:controller2: Listening to channel: deployments_events
> debug:controller1: Listening to channel: deployments_events
> info:controller1: HTTP ingress server listening on: http://localhost:8891
> debug:controller2: Listening on http://localhost:8894
> info:controller2: HTTP ingress server listening on: http://localhost:8891
> debug:controller1: Listening to channel: topics_events
> debug:controller2: Listening to channel: topics_events
**> error:controller2: Failed to LISTEN to topic_events_events: context canceled
> error:controller1: Failed to LISTEN to topic_events_events: context canceled
> warn:controller2: Failed to watch module changes, retrying in 100ms: context canceled
> warn:controller1: Failed to watch module changes, retrying in 100ms: context canceled
> ftl: error: serve failed: controller2 failed: listen tcp 127.0.0.1:8891: bind: address already in use**

**Comment by alecthomas** [comment]
The ingress server is now listening on 8891 @wesbillman
