### ISSUE TITLE
Codegen all known modules, not just dependencies

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1662]
In a project with a bunch of modules, it's currently very annoying adding an import for an FTL module, because not all modules are codegenned into the build directory. You have to:

1. Go up to the import section and manually enter the import, eg. `import "ftl/foo"`
2. Go back to a code block and reference a symbol in this module so that `goimports` doesn't remove it, eg. `foo.Bar`
3. Save your code.
4. Wait for FTL to rescan your module and codegen the missing module.
5. Finally you can use the module.

I think it might be a lot simpler to codegen all modules into a global shared directory, and just add this directory to all `go.work` files. That way all known modules will be available at all times.

**Comment by mistermoe** [comment]
i run into this regularly and it is indeed quite annoying. excited about the potential fix

**Comment by alecthomas** [comment]
We need to do some refactoring so this can be done more cleanly, specifically until #1741 is fixed.
