### ISSUE TITLE
Allow sending events from within an FSM state function

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1664]
Currently, sending an event to an FSM while the FSM is transitioning is invalid. However, sometimes the state itself knows what the next state should be.

We could either allow `Send()` to be used in this fashion directly, or add a new method `Next()` that fulfils this need.

- [x] [Resolve reference loops for `fsm -> funcs -> fsm.Next()`](https://github.com/TBD54566975/ftl/issues/2334)
- [x] Controller implementation.
    - [x] Encrypt payload
    - [x] Delete next rows if async call fails
- [x] Language runtime production support
- [x] Language runtime testing support
- [x] Documentation of feature + behaviour

**Comment by matt2e** [comment]
Confirmed with Moe, this is not a blocker for the current deadline anymore, they are using pub sub instead of FSM to get around this.
