### ISSUE TITLE
scheduledtask.go spews a lot of lease conflict debug logs

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1678]
Not sure why this is happening (probably incorrect errors being generated), it should all work fine:
- scheduler is checking if the error is a conflict and only logging at **trace** level
    - [code](https://github.com/TBD54566975/ftl/blob/matt2e%2Fpubsub-manager/backend/controller/scheduledtask/scheduledtask.go#L133)

Instead when I run ftl with `--log-level=DEBUG --controllers=5` i get this output:

> debug:func12: Failed to acquire lease: duplicate key value violates unique constraint "leases_key_key": conflict
> debug:func10: Failed to acquire lease: duplicate key value violates unique constraint "leases_key_key": conflict
> debug:func12: Failed to acquire lease: duplicate key value violates unique constraint "leases_key_key": conflict
> debug:func11: Failed to acquire lease: duplicate key value violates unique constraint "leases_key_key": conflict
> debug:func11: Failed to acquire lease: duplicate key value violates unique constraint "leases_key_key": conflict
> debug:func10: Failed to acquire lease: duplicate key value violates unique constraint "leases_key_key": conflict

**Comment by alecthomas** [comment]
You sure this didn't happen after a laptop suspend/resume cycle?

**Comment by alecthomas** [comment]
This is behind a `if errors.Is(err, leases.ErrConflict) {` but is executing the else case for some reason, even though we see `: conflict` in the message. We should fix this.
