### ISSUE TITLE
FTL should do rolling updates not "down" then "up"

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1687]
When we deploy we bring down the old deployment and then bring up the new one.
If we try executing a async call (used by FSM / PubSub) during this time, the call will fail.
If they defined a retry directive, that will hopefully allow for a successful call later.

This is slightly different to retry cases because we know we didn't attempt it we don't need to be concerned about whether the user code is idempotent. We may want our own internal retry logic in this case. But probably also should be part of some wider thinking about active deployments.

**Comment by alecthomas** [comment]
This is a more general problem, we need to ensure that FTL can perform an incremental rollout while keeping both deployments active.
