### ISSUE TITLE
Figure out why Docker compose is failing in CI

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1722]
With so many integration tests, we're hitting this failure very very frequently now:

```
Error response from daemon: driver failed programming external connectivity on endpoint ftl-db-1 (77de40e71a5a9b79309209ca12abdb5f67ca1faefcab7fce30ceaa2891f560e0): Error starting userland proxy: listen tcp4 0.0.0.0:54320: bind: address already in use
```

It doesn't seem to be an issue with FTL itself, but it would be great to fix it because it's really annoying.

**Comment by gak** [comment]
Examples

https://github.com/TBD54566975/ftl/actions/runs/9460605277/job/26059731611#step:5:564
https://github.com/TBD54566975/ftl/actions/runs/9457427212/job/26051227590#step:5:585
https://github.com/TBD54566975/ftl/actions/runs/9457388106/job/26051102482#step:5:597
https://github.com/TBD54566975/ftl/actions/runs/9444996323/job/26011687680#step:5:573

Seen on "Integration Test" matrix and "Test Go"

**Comment by alecthomas** [comment]
@gak volunteered as tribute

**Comment by gak** [comment]
- The postgres port is always triggering the error.
- The port is not used immediately beforehand.

**Comment by gak** [comment]
`tcp6       0      0 10.1.0.110:54320        13.107.42.16:443        ESTABLISHED 592/provisioner`

**Comment by gak** [comment]
Processes are randomly choosing high ports as the source port, randomly hitting 54320. Just need to choose a lower port under that range.
