### ISSUE TITLE
LSP notify when current build completes

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1808]
Currently when making a change, it's basically impossible to know whether the FTL build has completed. So when you're in a build+test cycle, you often have to run tests multiple times, hoping the changes have completed.

**Comment by gak** [comment]
I was thinking of this the other day! Maybe have FTL in the status bar spin when working, and a tick or cross depending on the outcome?

**Comment by alecthomas** [comment]
Yeah I think that would be nicer than a popup message. Maybe it goes green when built, grey spinner when building? Something, not sure.
