### ISSUE TITLE
LSP automatically should insert required imports when completing

### ISSUE THREAD

**Issue by gak** [TBD54566975/ftl#1809]
eg when there are no imports in the file, and you complete a verb, an `import ( "context" )` would be added. Similar to `ftl/builtin` and `"github.com/TBD54566975/ftl/go-runtime/ftl"`, and correctly appending imports to existing blocks.

I think this is possible with `additionalTextEdits`.

**Comment by alecthomas** [comment]
This is a bug and will be solved by #1662. Once that's done, the Go LSP will do the correct thing.
