### ISSUE TITLE
Suppress output Window when FTL extension starts

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1826]
I don't know why this pops up but it's annoying and meaningless to me.

<img width="1136" alt="image" src="https://github.com/TBD54566975/ftl/assets/41767/417ac8bc-ec83-489f-b06d-73b1c75dc7c4">

**Comment by gak** [comment]
Should we just make this `always` by default?

**Comment by alecthomas** [comment]
I'm talking about the Output window not the dialogue box.

**Comment by gak** [comment]
Ah! Very good.
