### ISSUE TITLE
Easier FTL Controller Database Migrations

### ISSUE THREAD

**Issue by alec-brooks** [TBD54566975/ftl#1839]
Right now when managing a deployed FTL cluster, managing database migrations of the controller is a bit inconvenient. It involves copying the database migration files from the FTL repo and then running the migrations using dbmate.
It would be nice if there was some way to perform these migrations without having to do this as it becomes tricky when trying to manage multiple deployed environments with different versions.

I believe there is a tool called `ftl-initdb` that is used for local dev that has the migration files baked in for the given version. Perhaps the solution here is to allow that tool to take connection strings (it may do already), and have the binaries available somewhere for downloading, but I am not sure if this is necessarily the best path forward, I am open to other suggestions.

**Comment by gak** [comment]
As discussed, aim for a `ftl migrate` command which runs embedded migrations locally.
