### ISSUE TITLE
`ftl new` fails with an inscrutable error if the Go toolchain is not available

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1847]
```
🐚 ~/demo $ ftl new go . invoicing
info: 
ftl: error: exit status 128
```

**Comment by safeer** [comment]
Oh weird, I'm seeing this:
<img width="782" alt="Screenshot 2024-06-21 at 2 50 38 PM" src="https://github.com/TBD54566975/ftl/assets/828473/f8a2355d-c978-4e00-af5f-56d74d70f37c">

**Comment by alecthomas** [comment]
It may have been a different cause? Regardless, the output for whatever command is being lost and I think you want to use our `exec.Cmd.RunBuffered()` function wherever this is occurring.

**Comment by alecthomas** [comment]
Ah I see you are using it already...not sure then. I also couldn't reproduce it just now :\

**Comment by safeer** [comment]
Still can't repro this, so closing it out
