### ISSUE TITLE
Consider not being so strict about ftltest context option ordering

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1866]
- Currently we build the context in order that the options were provided
- This has caused confusion, such as with this example where it was not obvious why it didn't work:
```go

func newContext() (context.Context, *_dal.DAL) {
	ctx := ftltest.Context(
		ftltest.WithMapsAllowed(),
		ftltest.WithDatabase(dbHandle), // <--- Assumes we have DSNs
		ftltest.WithDefaultProjectFile(), // <--- Provides DSNs
	)

	dal := _dal.New(dbHandle.Get(ctx))

	return ctx, dal
}
```
We may want to always handle project file options first, which would solve this issue.

Alternatively we could detect that the project file option was provided after options that could make use of it so atleast we explain to the user what to change.

**Comment by alecthomas** [comment]
A common pattern is for the options to just populate an intermediate structure with data, then an initialisation phase actually constructs everything.
