### ISSUE TITLE
If FTL can't start for some reason, attempting to start it again results in failure to start + icon spinning

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1890]
The first start failed because PG was hosed. The second attempt failed with the following message, and the spinner just kept spinning forever. I had to restart.

<img width="1756" alt="image" src="https://github.com/TBD54566975/ftl/assets/41767/6d6d7ebd-da75-4324-8dbc-84d7da235731">

**Comment by gak** [comment]
Related, my attempt shows successfully built when intentionally crashing on startup:

<img width="241" alt="image" src="https://github.com/TBD54566975/ftl/assets/31338/75126c78-e994-43aa-a3b4-befd7dabb512">

<img width="1466" alt="image" src="https://github.com/TBD54566975/ftl/assets/31338/45127476-c1cf-4b08-a09a-549e7e459bfa">
