### ISSUE TITLE
Connect errors when load testing through `ftl dev`

### ISSUE THREAD

**Issue by deniseli** [TBD54566975/ftl#1899]
What I was doing: load testing verb calls through `ftl dev`, sending one call every 5-10ms for over a minute.

I got two types of Connect errors:
* `ConnectError: [unknown] Failed to fetch` at 5ms
* `ConnectError: [not_found] could not resolve reference echo.flakyEcho: not found` at 10ms

Environment:

Machine: Apple M2 Max, 64GB mem, running Sonoma 14.4.1
Browser: Chrome version 126.0.6478.114
Local git HEAD: b72546498950ed2589749999631892c95898d0f9
Local code changes: only frontend JS changes and one new verb in the `echo` module from `examples/go`

**Comment by matt2e** [comment]
> could not resolve reference echo.flakyEcho: not found
This is because the runner paniced and is restarting, schema filters by modules with active runners and so it cant find the schema types
