### ISSUE TITLE
Can't define enums in sub-packages

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1903]
I thought this was working, but it doesn't seem to be in practice.

We should also ensure that all types can be defined in sub-packages.

**Comment by deniseli** [comment]
Is this the [same](https://sq-tbd.slack.com/archives/C04P86U1B4N/p1718990552411079?thread_ts=1718945015.708649&cid=C04P86U1B4N) issue rooted in the fact that enums haven't been migrated to the new extractor yet?

**Comment by alecthomas** [comment]
Related, yes.

**Comment by worstell** [comment]
#2050
