### ISSUE TITLE
Load passwords from 1Password quickly

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1930]
Related to #1906

Turns out loading passwords from 1Password is _really_ slow, so having a mutex around it makes deployments take 10-20 seconds each.

A couple of ideas for solutions:

1. Change the 1Password provider to store all secrets in a JSON blob in a single password entry.
2. Block on the first password fetch to avoid spamming the authentication prompt, then parallel load the remainder.

**Comment by matt2e** [comment]
Fixed in this epic https://github.com/TBD54566975/ftl/issues/1951
