### ISSUE TITLE
Reenable secret validation.

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1972]
Steps to repro:
- Add a module that defines a secret
- Set the secret using `ftl secret set ...`

We get this error:
> ftl: error: unknown: declaration "secretname" not found

Looks like we are looking up the active schema before setting a secret and erroring if it is not found. And a schema is only active if it was successfully deployed with runners. But when creating a secret that has not been set yet it can not deploy.

**Comment by alecthomas** [comment]
Very surprising no test covers this...

**Comment by alecthomas** [comment]
@safeer when you take a look at this, mind adding an integration test for it please?

**Comment by matt2e** [comment]
Reverting here to unblock other changes I'm working on with secrets: https://github.com/TBD54566975/ftl/pull/1978

**Comment by matt2e** [comment]
oh and btw `ftl-project-dr.toml` you'll need to add back in a `name` value. I'd added that in with in a subsequent commit but that is lost due to the revert
