### ISSUE TITLE
`ftl init` fails for new projects

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2000]
### Repro steps
- `mkdir test`
- `cd test`
- `ftl init "test" .`

### Error:
> ftl: error: could not load project config for secrets manager: open /ftl-project.toml: no such file or directory

**Comment by matt2e** [comment]
Also causing the failure of `TestLifecycle` integration integration test

**Comment by stuartwdouglas** [comment]
Is this still an issue? I could not reproduce with the instructions above

**Comment by matt2e** [comment]
Looks like it was fixed here: https://github.com/TBD54566975/ftl/commit/1e695b0ca5da19b6651c46722e25ccf08f29299b
