### ISSUE TITLE
Secrets gone missing in prod

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2009]
Could be:
- We added the `ftl` tag but didn't migrate
    - Would we get an error if router has the list but provider can't read them?
- We moved to a db router but didn't migrate
- Obfuscation causing issues?
   - Came in later than the version they are on? (check)
- ASM syncing / caching causing issues?
   - Would we get an error if router has the list but provider can't read them?
- DB migration not working and we wiped the db?
- ...?

**Comment by bradleydwyer** [comment]
Consider adding logging around accessors and state of secrets on startup.

**Comment by matt2e** [comment]
Moving that to another ticket.
Closing this one for now unless we hear something from the other team
