### ISSUE TITLE
Production logs: "Failed to receive notification: conn closed"

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2032]
Logs: <link removed>

- Happens twice every few seconds
- Code is in `dal.notify.go` [here](https://github.com/TBD54566975/ftl/blob/main/backend/controller/dal/notify.go#L86) where we listen to events streamed from the db
- First thought is why is the connection closing...?

**Comment by wesbillman** [comment]
I wonder if there's a difference in the production set up that is causing timeout issues for long running connections.

**Comment by wesbillman** [comment]
Migrated the controller off of the `pg_notify` version in favor of polling. We might want to revisit this in the future.
