### ISSUE TITLE
Failed to heartbeat controller

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2046]
`failed to heartbeat controller: duplicate key value violates unique constraint "controller_endpoint_not_dead_idx": conflict`
<link removed>

Might be related to this one: https://github.com/TBD54566975/ftl/issues/2045

**Comment by matt2e** [comment]
Assigned it to me because I think the next steps are just seeing if other fixes (like controller not panicing when getting an error back from calling a verb) make this go away.

**Comment by matt2e** [comment]
Havent seen this error the past few times we restarted the controllers, closing for now

**Comment by matt2e** [comment]
This might be back...

**Comment by wesbillman** [comment]
Once we have a k8s env setup for local debugging, we should did into this again.

**Comment by matt2e** [comment]
Looks like this is the cause:
- Controller is alive
- We take down the controller
- We bring up another controller. The controller ends up having the same endpoint as the original controller
- New controller tries to heartbeat the db
    - This fails because there is already a `controller` row with `state = 'live'` and a matching controller key
- A controller runs the `reapStaleControllers` job which finds live controller in the db which haven't been seen in the past 10s. Maybe the first time this happens we are still in the 10s window. But it shouldn't take long for one of these jobs to find and mark the old controller's row as `dead`
- New controller keeps trying to heartbeat, and will eventually succeed in upserting its row into the db.

You can repro locally by doing this:
- Commenting out code in the `if !recraete` block: https://github.com/TBD54566975/ftl/blob/main/backend/controller/sql/databasetesting/devel.go#L76
- Making the integer used for the controller's key random like it is in non-local environments: https://github.com/TBD54566975/ftl/blob/main/cmd/ftl/cmd_serve.go#L122

When I did this, the first heartbeat failed like in the issue description, then the staler controller was reaped, then the next controller heartbeat worked. Seems like everything recovered fine.
