### ISSUE TITLE
Auto-commit happens even if tests fail

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2057]
<img width="945" alt="Screenshot 2024-07-12 at 1 24 41 PM" src="https://github.com/user-attachments/assets/2c8fa054-e7f5-4ff8-be20-65f660c55f4f">

**Comment by wesbillman** [comment]
Maybe we should disable auto commit until we have a solution here?

**Comment by wesbillman** [comment]
![Screenshot 2024-07-16 at 10 29 25 AM](https://github.com/user-attachments/assets/28fb42e1-a09d-4bf3-9f98-855981ff528f)
I enabled this on our `main` branch. Will try auto merging today to make sure it works.
