### ISSUE TITLE
In dev v285.x had a waitgroup panic

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2063]
From the logs:
/home/runner/go/pkg/mod/github.com/!t!b!d54566975/ftl@v0.281.3/internal/modulecontext/module_context.go:206 +0x1c5
created by github.com/TBD54566975/ftl/internal/modulecontext.grpcModuleContextSupplier.Subscribe in goroutine 1
/home/runner/go/pkg/mod/github.com/!t!b!d54566975/ftl@v0.281.3/internal/rpc/rpc.go:252 +0x262
github.com/TBD54566975/ftl/internal/rpc.RetryStreamingServerStream[...]({0x127c930, 0xc00040a550}, {0x0, 0x0, 0x0, 0x0, 0x0}, 0xc0003bc200, 0xc000118648, 0xc00033a4a0, ...)
/home/runner/go/pkg/mod/github.com/!t!b!d54566975/ftl@v0.281.3/internal/modulecontext/module_context.go:242 +0x8f
github.com/TBD54566975/ftl/internal/modulecontext.NewDynamicContext.func2({0x126d180, 0xc0003bd200})
/home/runner/.cache/hermit/pkg/go-1.22.2/src/sync/waitgroup.go:87
sync.(*WaitGroup).Done(...)
/home/runner/.cache/hermit/pkg/go-1.22.2/src/sync/waitgroup.go:62 +0xd8
sync.(*WaitGroup).Add(0x126d180?, 0xc0003bd200?)
goroutine 51 [running]:
{"level":"error","attributes":{"module":"kcc","scope":"kcc","deployment":"dpl-kcc-161a9z4k3cc0kvdv"},"time":"2024-07-12T07:25:17.991920295Z"}
panic: sync: negative WaitGroup counter

I thought this would have been fixed earlier here, but is it still happening?
[fix: module context errors should not cause a negative wait group (](https://github.com/TBD54566975/ftl/commit/a8bc627b9f429bc1f8dede9e1e74c0ba13beca76)

cc @alec-brooks

**Comment by jonathanj-square** [comment]
This issue appears to have been reported against a version that does not include fix: https://github.com/TBD54566975/ftl/commit/a8bc627b9f429bc1f8dede9e1e74c0ba13beca76

That fix puts both `await.Done` calls behind `ReleaseOnce` as a means of guarding against multiple invocations. 

Furthermore, the stack notes call this site as the coordinate for the failure:
/home/runner/go/pkg/mod/github.com/!t!b!d54566975/ftl@v0.281.3/internal/modulecontext/module_context.go:`242` +0x8f
github.com/TBD54566975/ftl/internal/`modulecontext.NewDynamicContext.func2`

The line number noted is `242`; however, the new line number for this `await.Done` call is `244`. Prior to this fix the line number was `242`.  

The nested method name noted is `modulecontext.NewDynamicContext.func2`; however, the new name is `modulecontext.NewDynamicContext.func2.1` given this call to `await.Done` is now embedded inline of `modulecontext.NewDynamicContext.func2` after the fix. Prior to the fix it was contained directly in the body of `modulecontext.NewDynamicContext.func2`.
