### ISSUE TITLE
Module showed the old schema for `ftl schema get` even though it built successfully as part of deploy process

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2098]
After this: https://github.com/TBD54566975/ftl/issues/2095

Module MM shows old schema when calling `ftl schema get` even though it had been successfully built in the deploy process

Initial thoughts:
- If it was just built then it seems ok that the old schema is showing up here because we return the active schema (ie active runners > 0)
- ... but we had started to wait for new deployments of MM to come up, which would normally cause the old deployments to be taken down and new ones to come up... but this seems to indicate that the old ones are still active? Why are old ones still active?

**Comment by bradleydwyer** [comment]
A snapshot of the DB is available if necessary.

**Comment by matt2e** [comment]
Fixed in https://github.com/TBD54566975/ftl/pull/2110
