### ISSUE TITLE
Deploying modules which contains a subscription name change may cause issues

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2099]
When deploying through this issue: https://github.com/TBD54566975/ftl/issues/2095
- The changes in MM included a subscription name change
- In theory this would simply lose some state as the name is used to maintain state
- In reality this hits our code where that triggers when a deployment goes from 0->1 active runners, and from 1->0 active runners where we set up / destroy subscriptions (and maybe other things)
- Could this be causing issues?
- Are there any logs that would show that?

**Comment by matt2e** [comment]
subscriptions table still showed the old subscription name, and didn't have the new one.
This may hint that this subscriptions was the cause, or it may just be a result of the fact that the old module wasn't taken down and the new one wasn't deployed successfully.

**Comment by bradleydwyer** [comment]
A snapshot of the DB is available for review if necessary.

**Comment by matt2e** [comment]
Seems to be fixed by https://github.com/TBD54566975/ftl/pull/2110 and was not subscription related
