### ISSUE TITLE
Sync asm secrets with db resolver references

### ISSUE THREAD

**Issue by safeer** [TBD54566975/ftl#2104]
Currently, nuking / recreating the db removes all references to asm secrets, which means all secrets need to be set again. Client team has had to do this a few times.

Since we're tagging all asm secrets with "ftl", we can fetch them and add their refs to the db. Perhaps at first load / if we have zero refs?

**Comment by deniseli** [comment]
That's a great idea

**Comment by safeer** [comment]
Alternative: introduce something like
`ftl secret --asm --sync <s1,s2,..>`

This allows client teams to bring in specific secret refs from asm more intentionally.

**Comment by jonathanj-square** [comment]
The team does not think there is work to be done here if we incrementally update the db instead of performing wipes.
