### ISSUE TITLE
PollDeployments using cancelled context

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2112]
`failed to get deployments: context canceled` gets logged once every 10 seconds
- Seems to have happened after the second successful deploy of our partner project in production
- We did another deploy of all modules after this and it succeeded without issue while these logs continued

**Comment by jonathanj-square** [comment]
this may be repro'd locally by doing and killing ftl dev locally.

**Comment by matt2e** [comment]
I had `ftl dev` sitting idling for a while with our partner project's code, and somehow hit this issue. Not sure how to repro though... I couldn't hit it again.
@jonathanj-square I'm not sure how to follow your steps, since killing `ftl dev` wouldn't allow the issue to keep happening?

**Comment by wesbillman** [comment]
Fixed in #2127
