### ISSUE TITLE
Decide on pg notify use and clean up

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2156]
- Is pg notify something we want to use?
- If not, we should remove the db hooks and the unused code in `notify.go`

**Comment by matt2e** [comment]
Originally this issue was about stopping error logs.
I thought this was causing lingering error logs of `Failed to receive notification: conn closed`, but thats not true. It was just still coming from staging env because we hadn't updated FTL there.
Updating this issue to to be more about cleaning up after we decide on whether to use pg notify longer term or not

**Comment by stuartwdouglas** [comment]
What was the decision here? Given the lack of support for this on AWS and the potential need to support AWS it seems like removing it might be the best course of action.

**Comment by matt2e** [comment]
I vote remove it as well
