### ISSUE TITLE
Ability to reset a subscription to the head of a topic

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2175]
Partner project had this situation arise:
- Bad events were published to a topic overnight
- Subscription was hitting errors, and so fell far behind the topic as it slowly retried and finally gave up on each event

@mistermoe requested the ability to reset a subscription to the head of a topic to reset it

Would this be CLI and admin console?

**Comment by alecthomas** [comment]
Yeah that sounds like a CLI command to me.
