### ISSUE TITLE
Need a mechanism to handle asynchronous call failures (pubsub, cron, FSM, etc.)

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#2185]
Ideally a single mechanism that can be applied to all of them, rather than specific solutions for each such as a dead letter topics for pubsub.

Possible ideas:

- Add an `ftl.LastRetry(ctx)` function that can be used to detect if the current retry is the last one.
- Modify `//ftl:retry` to support a "catch" verb that will be called on complete failure.

**Comment by matt2e** [comment]
> won't work for PubSub
How come?

**Comment by matt2e** [comment]
Plan:
- add a catch verb definition to `//ftl:retry` directives
- add a state to async calls called `catching` when retries have been exhausted. Lease won't be released for the async call until the catch verb is called.
- async call doesn't complete until catch verb succeeds

Future plans:
- Add new request struct for catch verbs that includes error, retry metadata, call verb, request body, etc

**Comment by matt2e** [comment]
Removing P0, Moe said they won't have time to use it this week
