### ISSUE TITLE
otel: figure out how to get all metric descriptions propagated to datadog

### ISSUE THREAD

**Issue by deniseli** [TBD54566975/ftl#2203]
This one that we created doesn't show a description: https://app.datadoghq.com/metric/summary?metric=requests
But this one does: https://app.datadoghq.com/metric/summary?filter=grpc.se&metric=istio.grpc.server.handled.count

**Comment by deniseli** [comment]
priority: should come right after all the other otel work we have planned

**Comment by jonathanj-square** [comment]
Flare submitted to datadog team, awaiting a follow-up from their eng team

**Comment by jonathanj-square** [comment]
The flare did not result in RCA discovery, closing this out for now
