### ISSUE TITLE
otel: add a dashboard with the standard connect metrics

### ISSUE THREAD

**Issue by deniseli** [TBD54566975/ftl#2205]
https://github.com/connectrpc/otelconnect-go gives us a bunch of metrics + dashboard for free, so we should use that

**Comment by deniseli** [comment]
https://app.datadoghq.com/dashboard/39r-qfe-r4w/ftl?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1722879202642&to_ts=1722882802642&live=true

And from https://www.datadoghq.com/blog/grpc-testing-datadog-synthetic-monitoring/, https://app.datadoghq.com/synthetics/tests?_gl=1*kql5ix*_gcl_aw*R0NMLjE3MjA0OTM1MzIuQ2p3S0NBanduSzYwQmhBOUVpd0FtcEhadzJmc3NzVm5mWmJya054T1N4Yk9RTnJQUjNpNzVLTllqVm5XVzN1bUJvbjJQNGhJcDlDUmFCb0N0cmNRQXZEX0J3RQ..*_gcl_au*MTU3Mjc0NTQ5Ny4xNzIwNDg2OTgw*_ga*MTY2NTI2NDQ5Ny4xNzIwNDg2OTgw*_ga_KN80RDFSQK*MTcyMjg4MjcxNi45LjAuMTcyMjg4MjcxNi4wLjAuMTA4NjQyNjU.*_fplc*JTJGcVRQZUZZb1ZtQ2E1bEZUSnMlMkIwVHpnUERpR1ZqN05WamRnTlBoOUFLVDNyRjRvZkM2RFRMdGprJTJCVU4yNDl6aUpjNEhldEElMkZNRW9IUzVZcTQ5Zm5LbTlnQ1M0eEZDMGhkZ3VYcCUyRk1rcDdGeDkydnlKZW1oOHBGVFJhZlhCdyUzRCUzRA..&_ga=2.144149238.2122763220.1722882716-1665264497.1720486980

**Comment by safeer** [comment]
Added some monitors to the dashboard:

https://app.datadoghq.com/dashboard/39r-qfe-r4w/ftl?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1722881221194&to_ts=1722884821194&live=true
