### ISSUE TITLE
`ftl-controller` should produce a meaningful error message when required args are not specified

### ISSUE THREAD

**Issue by jonathanj-square** [TBD54566975/ftl#2206]
The controller fails with a segmentation fault when the `--advertise` argument is omitted and there is no environment variable to fall back on. When setting up leaders the controller seg-faults when attempting to reference the corresponding parameter. Instead the controller should report the missing argument.

It may be worth while to audit the other controller arguments to make sure this unwanted behavior isn't present for them too.

To repro:

launch `ftl-controller` without specifying any arguments.

```
> ftl-controller

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104d9e578]

goroutine 7 [running]:
net/url.(*URL).String(0x0)
	/Users/jonathanj/Library/Caches/hermit/pkg/go-1.22.5/src/net/url/url.go:817 +0x28
github.com/TBD54566975/ftl/backend/controller/leader.(*Coordinator[...]).Get(0x105dfd020)
	/Users/jonathanj/dev/ftl/backend/controller/leader/leader.go:135 +0x184
github.com/TBD54566975/ftl/backend/controller/leader.(*Coordinator[...]).sync(0x105dfd020, {0x105de7078, 0x140004a4270})
	/Users/jonathanj/dev/ftl/backend/controller/leader/leader.go:108 +0x108
created by github.com/TBD54566975/ftl/backend/controller/leader.NewCoordinator[...] in goroutine 1
	/Users/jonathanj/dev/ftl/backend/controller/leader/leader.go:94 +0x17c
```

This stack points to the following expression:

`lease, leaderCtx, leaseErr := c.leaser.AcquireLease(c.ctx, c.key, c.leaseTTL, optional.Some[any](c.advertise.String()))`

where `c.advertise.String()` is presumed to be the culprit.

**Comment by stuartwdouglas** [comment]
How can I reproduce this? config.SetDefaults() looks like it should set this to the bind address, but it might not be called in all places.
