### ISSUE TITLE
Allowing `catch` to work with `any` request types

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2213]
Currently when declaring a retry with a catch, the catch verb must include the exact request type. eg:
```go
//ftl:verb
//ftl:retry 1 1s catch catchExample
func Example(ctx context.Context, req ExampleRequest) error {...}

//ftl:verb
func CatchExample(ctx context.Context, req builtin.CatchRequest[ExampleRequest]) error {...}
```

This prevents these use cases:
- Defining a single catch verb that can be used for multiple retryable verbs (assuming they don't have the exact some request type)
- Defining a catch in FSM's retry directive, as each transition has different event types

It could be useful to have a catch verb with takes `builtin.CatchRequest[map[string]Any]` or just `builtin.CatchRequest[Any]`.

Something to be careful about:
- A failing catch verb  currently retries forever
- If a request can't be unmarshalled into the request type at runtime we could easily end up repeatedly failing forever...

**Comment by alecthomas** [comment]
I think allowing `Any` makes sense.

**Comment by matt2e** [comment]
decision: Allow Any or exact match
