### ISSUE TITLE
Add ability to configure retries when acquiring a lease

### ISSUE THREAD

**Issue by deniseli** [TBD54566975/ftl#2220]
From @mistermoe:

> Do FTL Leases incorporate the concept of a spin lock? aka "attempt to acquire the lock n times before actually failing?" If not, is this something you'd be open to providing the ability to configure when acquiring a lease? Would be cool if `ftl.Lease` accepted an optional argument `ftl.Spin(duration)` or something along those lines

**Comment by alecthomas** [comment]
Discussed offline and this isn't necessary at this stage.
