### ISSUE TITLE
Runner failed to reserve

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#2250]
We saw this during a production deploy:

```
Failed to increase deployment replicas: failed to reserve runner for dpl-kcc-ktzil2tlxybtwdj: failed request to reserve a runner for dpl-kcc-ktzil2tlxybtwdj at http://10.2.135.82:8893/: unknown: can only reserve from IDLE state, not RUNNER_ASSIGNED
```

**Comment by matt2e** [comment]
We saw this again yesterday. Restarting the runners was enough to fix the issue.

**Comment by alecthomas** [comment]
We'll be completely rewriting this code soon, so I don't think there's a pressing need to fix it.

**Comment by stuartwdouglas** [comment]
I am closing this, that code path no longer exists.
