### ISSUE TITLE
otel: instrument observability (metrics + traces) on the database

### ISSUE THREAD

**Issue by deniseli** [TBD54566975/ftl#2285]
From https://github.com/TBD54566975/ftl/issues/2194#issuecomment-2274154832:

### Immediate Needs
For metrics in DD, the well-lit path appears to be DD's [official Postgres integration](https://docs.datadoghq.com/integrations/postgres/?tab=host). That comes with not only all the core metrics we want, but also a nice dashboard. For immediate use cases, this is definitely the best solution. Next step on that is talking to @bradleydwyer 

If we cannot do that^, then we'll need to instrument custom metrics right now, which is possible but not ideal, both because of the implementation time and also because of the added complexity to the sql code (much of which is generated by sqlc, so we can't just do _whatever_ we want to make the interface nice/intuitive).

### Long Term
That said, FTL is not tied to DD, so in the long run, we’ll likely want some integration for this outside of the DD world as well. The first reasonable avenue for this was otel's [zero code instrumentation for Go](https://opentelemetry.io/docs/zero-code/go/). Unfortunately, that integration only supports traces right now, not metrics. The whole project is marked as a work in progress, but there doesn't appear to be any immediate plans to add metric support.

The urgency for supporting non-DD database metrics is fairly low. Our current customer team and next customer team are both internal, so they should both use DD. Most likely, the next one after that will be as well. We will want to lift this instrumentation out of the DD-only world before significant amounts of open source development, but perhaps otel will also provide better built-ins for instrumenting database metrics by then. This seems like something we can afford to wait for.

Parent doc link for zero-code: https://opentelemetry.io/docs/concepts/instrumentation/zero-code/

**Comment by alecthomas** [comment]
A simpler path is probably to switch to using the standard library's sql API and use OTEL's [instrumentation for that](https://github.com/XSAM/otelsql).

We're currently using sqlc's pgx5 driver because it supports bulk inserts (IIRC?), but we can likely work around that.

**Comment by deniseli** [comment]
Niiiiice that looks fantastic! From some brief grepping, I couldn't find any `INSERT`s in the current code that would cause issues, and it looks like there are plenty of ways to [`COPY`](https://pkg.go.dev/github.com/lib/pq#hdr-Bulk_imports) without relying on sqlc's `:copyfrom` (which we don't even use now).

It seems like the biggest thing we'd be losing is the codegen. What do you think would be the best way to move forward with the existing `queries.sql` files, if we went down that route? Start manually modifying the files that were generated by sqlc, and delete the `queries.sql` files they were generated from?

**Comment by deniseli** [comment]
Notes from standup: we don't need to remove sqlc, just switch out the driver. :)

**Comment by deniseli** [comment]
reopening until we can unrevert the revert
