### ISSUE TITLE
Improve otel-stream usability for local metrics troubleshooting

### ISSUE THREAD

**Issue by jonathanj-square** [TBD54566975/ftl#2364]
Troubleshooting metrics instrumentation via `otel-stream` is slow and cumbersome. Console output is not ideal for this task and the rate at which metrics are collected is also too slow (logs are collected once per minute by default).

We should shift to a stack like Grafana that provides a UI for visualizing metrics.

**Comment by gak** [comment]
Look into the environment variable for collection period.
