### ISSUE TITLE
Investigate prod verb call failures caused by `dal.GetActiveSchema` returning an error

### ISSUE THREAD

**Issue by deniseli** [TBD54566975/ftl#2431]
A number of prod verb calls have been failing ([Datadog](https://app.datadoghq.com/metric/explorer?fromUser=false&graph_layout=split&start=1723491807390&end=1724096607390&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGniqyIIIaAB0mRho9UZBGhbAAFQ8dRgaTpn4IggAFACUIDwAulSu7niYoeFzqgsYMaXxkzMg7VhoOaDyTYgIOUk4MAOLGhCZiWiicE5yiuU4j1APT070TMoiNweNCTfgQeyYLAvBTnR4iJTTHh8XbyR4IADCUmEMBkKLRTigPjgIlujmsoCkzxg2gw8kYTkU2mUNXqjWadUEGAgaDwRicqhwAm2VEeqnEKAATAAWKjpbSECnaARM3ICDT3JE8IA)) due to [schema retrieval errors](https://github.com/TBD54566975/ftl/blob/main/backend/controller/controller.go#L998). This is probably worth a brief investigation.

**Comment by deniseli** [comment]
better chart: https://app.datadoghq.com/metric/explorer?fromUser=false&graph_layout=split&start=1723491807390&end=1724096607390&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGniqyIIIaAB0mRho9UZBGhbAAFQ8dRgaTpn4IggAFACUIDwAulSu7niYoeFzqgsYyoraTowZI7HxE9NU7VhoOaDyTYgIOUk4MAOLGhCZiWiicE5yiuU471BvD5OehMZQiNweNCTfgQeyYLBfBS3d4iJTTHh8EBw8QAYSkwhgMix8neCCcUB8cBEz0c1lAUk+MG0GHkjCcm2UNXqjWadUEGAgaDwRicqhwAkmMxA71U4hQACYACzHNyEenaATaZQCDSvDE8IA

**Comment by stuartwdouglas** [comment]
This has been moved out of the call path so should no longer be an issue.
