### ISSUE TITLE
Add page(s) to display ftl status type information (controllers, runners, deployments, etc.). Deployment state/control/history

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#2446]
We'll need to sketch out this experience a bit to make navigating this information useful to users.

For example, should we view the system from the lens of realms and modules etc? Or from the lens of deployments as we currently do. Or should we just have a basic "Status" page for now that formats the data we already show in `ftl status` in cli?

**Comment by wesbillman** [comment]
Status page added here #2588

I'm sure this will evolve over time, but for now we can see status! 🥳
