### ISSUE TITLE
Evaluate and implement TanStack table

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#2460]
The tables in the console have lots of little UX issues. We should look into integrating [TanStack table](https://tanstack.com/table/latest) (or something else awesome) so that we can avoid many of the common table issues.

**Comment by deniseli** [comment]
From a brief glance:

Pros:
* Interface is idiomatic and straightforward

Cons:
* Built to be used with the `<table>` element type, which is severely limiting:
    * Render slower, to an extent that's incredibly problematic for full-page tables with many rows and more complex content. Related: lazy loading tends to work pretty poorly with dynamic re-rendering of rows in a `<table>`, or at least I've never personally found a workaround.
    * Limits formatting to a really basic grid. You can't interleave intermediate rows (e.g. section headers, click-to-expand blocks) without aggressive CSS hacks that get horrendous to maintain.
    
Notes from quick sync:
* Current tables in the console are actual `<table>`s, not divs.
* We're mainly interested in ironing out some layout bugs with the existing table displays
* I'll take a quick look at whether tanstack helps with any of that, but mostly expecting that whether we use tanstack or not, we'll need to fix the layout issues with some CSS
* I'll take a quick pass at fixing the current bugs with CSS.
* We'll want to redesign the deployments page, including possibly the inflow UX to the page (e.g. start with modules?)

**Comment by deniseli** [comment]
For the future: this is a nice table alternative if we want to use a library: https://www.ag-grid.com/react-data-grid/getting-started/

**Comment by deniseli** [comment]
Fixing alignment of flex-width columns: https://github.com/TBD54566975/ftl/pull/2463
