### ISSUE TITLE
How will we support schema evolution (changes to builtins)

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#2476]
We recently had a challenging deploy since the structure/format of `builtin.HttpRequest/Response` changed. This caused deployments to start failing and we were unable to redeploy.

In order to get things working again, we had to delete the `deployments` table in postgress as well as `event` related tables.

**Comment by deniseli** [comment]
closing since this is a more general problem to solve holistically

**Comment by deniseli** [comment]
should be included in discussions around versioning
