### ISSUE TITLE
Java verb calls don't have a way to stop when cancelled

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2509]
Java does not currently have a way to stop execution of the call that gets canceled, so it will always continue even when the async call's lease expires.

Go does this by cancelling the context when the call grpc request ends, so when a verb tries to use the context things should fail.

Speaking with @stuartwdouglas last week, it sounds non-obvious as to the best way to do this in Java.

**Comment by matt2e** [comment]
Test is disabled for this for java here: https://github.com/TBD54566975/ftl/blob/main/backend/controller/pubsub/integration_test.go#L205

**Comment by gak** [comment]
Tricky in Java. Will revisit if needed.
