### ISSUE TITLE
Better visibility on ingress errors

### ISSUE THREAD

**Issue by gak** [TBD54566975/ftl#2517]
```logger.Debugf("bad request: %s", err.Error())``` in ingress handler does not mention the verb involved and is difficult to know which request has failed in production.

This is related to a webhook coming in and erroring, but the user can not observe exactly why/how it failed. This is also very handy when you have little feedback from a webhook provider.

**Comment by jiyoontbd** [comment]
example error message:
```bad request: 0:0: expected array, got string```
