### ISSUE TITLE
Add timeline records for `ingress` requests that failed before being called

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2518]
Use case we are seeing from our partner project:
- A bad call came into the API
- They want to see the content of the request to find out what went wrong
- They can not find out because we did not save a timeline record for the call

Code details:
- this is the early exit: https://github.com/TBD54566975/ftl/blob/main/backend/controller/controller.go#L1019
- this is where we add the call to the db: https://github.com/TBD54566975/ftl/blob/main/backend/controller/controller.go#L1092

**Comment by alecthomas** [comment]
We can't record it as a "call" event because that event needs the response, but we should create an "ingress" event and record that.

**Comment by alecthomas** [comment]
I think it would make more sense to be a separate event, regardless. An ingress request is inherently separate to the Verb call that services it.

**Comment by wesbillman** [comment]
https://github.com/TBD54566975/ftl/issues/2521
