### ISSUE TITLE
VSCode extension release fails

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#2536]
Example [here](https://github.com/TBD54566975/ftl/actions/runs/10607258263/job/29399390011). Looks like it's still using npm and should be switched to pnpm too? 

If possible let's also add something to the PR pipeline that verifies that this step _will_ succeed on release.

**Comment by wesbillman** [comment]
I think this might be a cache issue. I'm going to watch this next release to see how it goes
