### ISSUE TITLE
Docker build fails on linux due to dockerignore and git ls-files conflict

### ISSUE THREAD

**Issue by AlexSzlavik** [TBD54566975/ftl#2632]
Docker image builds are broken on Linux due to the inclusion of `/**/.idea` in .dockerignore. Docker build will not copy the .idea directory, and the following step fails during build. Not sure why this doesn't fail on MacOS. 

https://github.com/TBD54566975/ftl/blob/14f4a371ad8011284d1e4031d734badd9176f23d/Dockerfile.controller#L24

# Reproduce
`just build-docker controller` on a linux system.
Tested that this is the issue by commenting out .idea in .dockerignore. 

# Suggested fix
Omit files in .dockignore when performing the timestamp reset step above.

**Comment by alecthomas** [comment]
Want to just send a PR?

**Comment by alecthomas** [comment]
Although, this seems to work fine in CI: https://github.com/TBD54566975/ftl/actions/runs/10736216723/job/29775141104

**Comment by AlexSzlavik** [comment]
Happy to, just ran out of time tonight and didn't want to forget.

**Comment by AlexSzlavik** [comment]
Yea, that's the thing I couldn't reconcile either. I imagine it's something in my env, but conceptually I think something is off. The touch should create the file if it doesn't exist, but i still think that's technically incorrect, since the build wanted to ignore those files.

**Comment by AlexSzlavik** [comment]
So apparently I wasn't using docker's BuildKit component (on my Arch Linux setup) to build, which led to bizzare issues. Closing since it works after all.
