### ISSUE TITLE
Duplicate data elements in verb schema

### ISSUE THREAD

**Issue by tomdaffurn** [TBD54566975/ftl#2648]
Looking a verb that has Ref type request and response which is the same type, the data element is duplicated. Doesn't happen when response type is different to request type.

<img width="737" alt="image" src="https://github.com/user-attachments/assets/75763855-a8dd-4f3c-8152-5b316617324f">

**Comment by alecthomas** [comment]
I suspect this is specifically talking about the console rendering of the schema, rather than the schema the controller sees?

**Comment by tomdaffurn** [comment]
Yeah I saw it in console first. I'll check what the controller reports tonight.

**Comment by tomdaffurn** [comment]
`ftl schema get` is showing correct stuff. Seems like console extracts the request and response type for a single verb, and doesn't check if they're the same type
