### ISSUE TITLE
console module tree improvements

### ISSUE THREAD

**Issue by deniseli** [TBD54566975/ftl#2760]
* [x] dump headlessui disclosure button and make the expansion state externally controlled. This should fix the expansion state bugs
* [x] add top filters for decl type and substring match.
  * [x] make sure modules with nothing inside them are handled in some reasonable way. Consider graying them out and/or sorting to the bottom of the list. Might not want to do these things if it makes the UI feel jumpy. Need to play around with it

**Comment by wesbillman** [comment]
For the top filters, I think the decl type filtering would be awesome! For the substring match, we should just check that it's useful given the global search we have now. If we decide it's still good to add, we can likely share fuzzy search logic between this filter and the global search :)

**Comment by deniseli** [comment]
sweet sg!
