### ISSUE TITLE
Style verb page content and fix layout issues

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#277]
For a first pass at VerbTab we can have a layout like this

- [x] VerbForm (response should be syntax highlighted)
- [ ] RequestGraph for the last request made by the form above ^
- [ ] Section to describe the verb (basically the syntax highlighting we have there today)
- [ ] Call list with much better layout/formatting

**Comment by wesbillman** [comment]
Also, #311 might be related as well.

**Comment by EdwardIrby** [comment]
@wesbillman I'm guessing this is more relevant now with the new module page interface and interactions so I'll work this in.
