### ISSUE TITLE
Java `enum` is schema extracted as `data`

### ISSUE THREAD

**Issue by tomdaffurn** [TBD54566975/ftl#2787]
Java enum classes are turned into schema type `data`. Special handling is needed to detect Enums as distinct from Classes:

https://github.com/TBD54566975/ftl/blob/06a05f540f0735958c4839a9ebce1b71cdbb6eb4/jvm-runtime/ftl-runtime/common/deployment/src/main/java/xyz/block/ftl/deployment/ModuleBuilder.java#L296

Should use `info.isEnum()`

**Comment by stuartwdouglas** [comment]
There is an issue about adding support for enums here: https://github.com/TBD54566975/ftl/issues/2514

**Comment by tomdaffurn** [comment]
Dupe of https://github.com/TBD54566975/ftl/issues/2514
