### ISSUE TITLE
Pressing ^D doesn't work in `ftl dev` (but does with `ftl interactive`)

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#2809]
The first time it prints "exit" but doesn't exit, the second time it wedges the console making it unresponsive :(

```
> exit
> ^D
```

**Comment by stuartwdouglas** [comment]
This will be fixed by https://github.com/TBD54566975/ftl/pull/2817

**Comment by stuartwdouglas** [comment]
Actually it was already fixed by https://github.com/TBD54566975/ftl/pull/2810
