### ISSUE TITLE
ftl dev panics if another dev instance is already running

### ISSUE THREAD

**Issue by worstell** [TBD54566975/ftl#2902]
should provide better error messaging

<img width="1099" alt="Screenshot 2024-09-30 at 10 45 26 AM" src="https://github.com/user-attachments/assets/1dea7571-fe37-4b7e-9fc2-543af1c804a5">

**Comment by deniseli** [comment]
I wonder if this is what's causing `just e2e-frontend` to fail when `ftl dev` is already running in a separate tab
