### ISSUE TITLE
Centralise buildengine build update logic

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2937]
Each time a build starts/fails/succeeds we have to:
- log the update
- tell `e.listener`
- tell the CLI status manager

It's easy to miss doing one of these in each case, or let the logs drift away from being consistent.

- Could logging be moved to the `e.listener` wrapper functions rather than being spread out?
- Can we support pubsub instead of a single listener?
- Can we connect the build engine and the CLI status manager via a listener?

**Comment by stuartwdouglas** [comment]
I think it might also be worth trying to remove the 'round' based processing, and move to a direct dependency model instead. The round based approach means that some deployments can end up waiting for unrelated deployments in the earlier round.
