### ISSUE TITLE
`ftl new go` should explain envar usage for platforms 

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2938]
GOOS and GOARCH should be mentioned in the help text

**Comment by alecthomas** [comment]
We don't want users to use these actually, we want it to be reflected from the clsuter.

**Comment by matt2e** [comment]
Is that happening soonish do you think? One of the loose ends with the language plugin stuff is to make sure envars gets passed alongand I think this was the main use case for that

**Comment by stuartwdouglas** [comment]
AFAIK the main usage of this currently is to run the kube tests locally on a MBP. Once we have https://github.com/TBD54566975/ftl/issues/1845 I don't think there will be any real need for the user to know about these.
