### ISSUE TITLE
`types.ftl.go` is using tabs not spaces

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2944]
Assuming we want to be consistent with the rest of our code with this.

(removed lines have spaces, added lines have tabs)
<img width="726" alt="Screenshot 2024-10-02 at 11 15 28 AM" src="https://github.com/user-attachments/assets/3124bd63-ce5f-4b38-a53b-69d65c9a9a39">

**Comment by wesbillman** [comment]
This should be expected [now that we're running](https://github.com/TBD54566975/ftl/pull/2927) `go fmt` on these `types.ftl.go` files after we generated them. `go` ❤️ `tabs` 😂

**Comment by wesbillman** [comment]
I'll close this as expected for now, but happy to reopen if I'm missing something here @matt2e 👍

**Comment by matt2e** [comment]
All good!
