### ISSUE TITLE
Duplicate log lines printed for cron, pubsub

### ISSUE THREAD

**Issue by safeer** [TBD54566975/ftl#2962]
Unsure if these are being executed twice or the logs just printed twice. Cron dupes visible in the console UI as well

<img width="695" alt="Screenshot 2024-10-02 at 1 48 13 PM" src="https://github.com/user-attachments/assets/03987dd7-4172-4164-8915-2212969af8b2">

**Comment by wesbillman** [comment]
I noticed similar behavior with logs as well:
```sh
info:cron: Hourly cron job triggered.
info:cron: Hourly cron job triggered.
info:cron: Frequent cron job triggered.
info:cron: Frequent cron job triggered.
```

**Comment by stuartwdouglas** [comment]
It's probably https://github.com/TBD54566975/ftl/pull/2919/files#diff-7a9ce4f8939ac436a713cd221b245a4e6465380d99d5834de728e23b09106590R444

I was thinking that we should have the errors in the pod logs as well as being sent back to the deployment logger, but for local dev that results in duplication.
