### ISSUE TITLE
Compact logs so they take up less space in the timeline.

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#306]
- [ ] Compact timeline into a more table-style layout. Each event should have its own icon/indicator. Logs should also indicate levels. Deployments should show type, etc.

Something like this...
![Screenshot 2023-09-07 at 4 42 34 PM](https://github.com/TBD54566975/ftl/assets/51647/78d139c3-8dc5-4f2b-b039-17eb3c1069a4)

**Comment by wesbillman** [comment]
#343 compacts all timeline entries a bit.

Will need to rebuild the timeline from scratch to support compacted logs...
