### ISSUE TITLE
All filtering for the timeline should be done on the backend

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#309]
The console timeline interface needs to expand to be able to support the type of interactions developers will need to debug issues.

Some of these filters exist on the backend already but are not piped through to the console service yet. Here's a full set just to ensure we cover everything.

- [x] Filter by log level. This is likely just a single file like `Debug` and above for example
- [x] Filter by event type. `Log`, `Call`, `Deployment`, `Scaling` etc.
- [x] Filter by modules. Probably need to support multiple modules
- [x] Filter for before and after an Event ID. This will allow us to do pagination as well as share links with a given event ID
- [x] Filter by time. Before and After
- [x] Limit rows. For pagination etc. we'll probably want to specify an ID (or zero if it's the first page) and get N rows before or after that ID

In addition, we'll need to be able to specify these filters for both a streaming endpoint and a synchronous endpoint

- [x] Filter via `StreamTimeline`
- [x] Filter via `GetTimeline` (this will need to be added to the console service)

**Comment by alecthomas** [comment]
Everything except migrating `StreamTimeline` was implemented in #374.

**Comment by wesbillman** [comment]
Should be all good now with the latest changes from today.
