### ISSUE TITLE
Store provisioned DSN secrets properly in a cluster specific default secret store

### ISSUE THREAD

**Issue by jvmakine** [TBD54566975/ftl#3114]
Currently provisioned DSN secrets are stored in "inline" secret store. However, we should have a cluster specific default store to store these.

**Comment by mistermoe** [comment]
[relevant code](https://github.com/tbd54566975/ftl/blob/main/backend/controller/controller.go#L1050)

**Comment by mistermoe** [comment]
i think this is done per the [recent changes](https://github.com/tbd54566975/ftl/blob/main/backend/controller/controller.go#L1060-L1069) you made @alecthomas ?

**Comment by alecthomas** [comment]
Yep!
