### ISSUE TITLE
subscriber stuck at `executing` state, no `async_calls` records being added

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/ftl#3216]
topics
```
463 | top-tbdex-rfqsTopic-2lkruzsfvro94hbi                  | 2024-08-21 19:35:13.240665+00 |         7 | rfqsTopic               | tbdex.RfqEvent               | 6607
```
topic_subscriptions
```
883 | sub-tbdex-rfqs-57qux2tvtswj1020                       | 2024-09-13 00:29:19.805551+00 |      463 |         7 |          1043 | rfqs                    |   6602 | executing
```

```
async_calls : no new rows were written
```

still "stuck" even after running `ftl pubsub subscription reset tbdex.rfqs --endpoint=https://tbd-ftl.tbd.sqprod.co/` 

relevant thread: https://sq-tbd.slack.com/archives/C06CW7P69EK/p1730133987466179

**Comment by matt2e** [comment]
Cleaned up prod. We had multiple issues all at once (prod had not been pushed to for a long time) including decryption issues.
