### ISSUE TITLE
reapAsyncCalls fails when keys are no longer valid

### ISSUE THREAD

**Issue by worstell** [TBD54566975/ftl#3221]
```
{
"level":"warn",
"attributes":{"scope":"reap-async-calls"},
"message":
   "failed to complete zombie async call: failed to finalize cron async call: 
    failed to get cron job \"crn-blah-29kltjo4n1eodt0d\": 
    failed to get cron job \"crn-blah-29kltjo4n1eodt0d\": 
    not found","time":"2024-10-28T20:40:46.852645771Z"
}
```

**Comment by matt2e** [comment]
@stuartwdouglas can you update the ticket with what you found out earlier today?

**Comment by stuartwdouglas** [comment]
We fixed this by cleaning up the database, but I think there are still cases where the database can get into a state where old cron jobs are removed but not async calls. 

I am going to change the way the delete code works so the delete happens by owner, rather than the last call id field.
