### ISSUE TITLE
Validate uploaded artifacts at deployment

### ISSUE THREAD

**Issue by jvmakine** [TBD54566975/ftl#3250]
Currently, if we upload an invalid binary (compiled for incorrect architecture, for example) the deployment just hangs, and runner ends up in crash loop, with error
```
ftl-runner: error: failed to spawn plugin: plugin process died: context canceled
```

It would be a better user experience to check the binary is in correct format, and if not, return an error indicating that during the deployment.

**Comment by alecthomas** [comment]
Duplicate of #1845
