### ISSUE TITLE
Allow db connection pooling

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#3281]
Request from @andresuribe87:

> I was trying to parallelize queries to the DB in golang. When testing, I saw errors of the sort conn busy. Some googling suggested that it might be related to concurrency issues with pgx - i.e. this can happen when not doing connection pooling. Perusing the FTL code, I noticed that [database.go](https://github.com/jackc/pgx/wiki/Getting-started-with-pgx#using-a-connection-pool) is registering the single connection pgx driver. Would you be amenable to changing that to a connection pool per what's suggested in [here](https://github.com/jackc/pgx/wiki/Getting-started-with-pgx#using-a-connection-pool)?

We would want module code to be able to choose the pooling parameters

**Comment by matt2e** [comment]
Issue may already be resolved...

**Comment by stuartwdouglas** [comment]
We already support connection pooling, however the config is hard coded.

Connection pool config will likely be part of the provisioner config, which is a big issue in itself, so I will close this for now.

**Comment by andresuribe87** [comment]
Thanks @stuartwdouglas 

 What's the suggested way to grab a handle to the DB from the module, such that it can be used concurrently? Any docs you could share, or examples, would be really helpful!

I wasn't able to figure that out. My impression from Pgx docs was that a single is not concurrency safe.

**Comment by stuartwdouglas** [comment]
The pooling should be provided by the golang sql package: https://github.com/TBD54566975/ftl/blob/be8d02fda1869c56c0aaeb39a083e98814301a5f/go-runtime/server/database.go#L67

The standard SQL library should be taking care of the pooling.
