### ISSUE TITLE
Improve speed of console e2e test

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#3286]
The console e2e test is now one of the [slowest tests](https://github.com/TBD54566975/ftl/actions/runs/11621049239/job/32364529533), taking almost 5m, mostly due to the downloading of Chrome. Let's fix this, or alternatively move the test to the release so it only runs at release time.

Some ideas:
- Create an image with Chrome pre-installed and specify that explicitly in the action.
- Move the task to release time.

**Comment by wesbillman** [comment]
This might not be fully fixed, but the chrome part is cached now. It seems like most of the time is spent in the `ftl dev --recreate` and running tests. I'll keep looking into ways to speed up the tests as well. 

~10s to download postgres
~30s to deploy modules
~60s to run tests

```
Mon, 04 Nov 2024 18:12:41 GMT
[WebServer] info: Starting FTL with 1 controller(s)
Mon, 04 Nov 2024 18:12:42 GMT
[WebServer] info: {"status":"Pulling from library/postgres","id":"15.8"}
Mon, 04 Nov 2024 18:12:42 GMT
[WebServer] info: {"status":"Pulling fs layer","progressDetail":

... Then the controller starts

Mon, 04 Nov 2024 18:12:51 GMT
[WebServer] info: Controller started in 1.003928724s

... Then all modules are deployed.

Mon, 04 Nov 2024 18:13:23 GMT
[WebServer] info: All modules deployed in 39.98s, watching for changes...

.. Then all tests are complete

Mon, 04 Nov 2024 18:14:28 GMT
  41 passed (2.1m)

```
