### ISSUE TITLE
Delivery guarantee when using ftl's pubsub?

### ISSUE THREAD

**Issue by jiyoonie9** [TBD54566975/ftl#3337]
When I use `//ftl: subscribe` and opt into consuming from an ftl topic, what's the delivery guarantee? Is it at least once, at most once, something else? Can I configure it? 

Tried to look first in https://tbd54566975.github.io/ftl/docs/reference/pubsub/ but could not find relevant info.

**Comment by alecthomas** [comment]
FTL topics are at least once. They're in the FTL database at the moment, but will soon be replaced by Kafka topics and have the same semantics as Kafka, effectively.

**Comment by matt2e** [comment]
I'll add it to the docs to make it clear
