### ISSUE TITLE
CLI feels much slower than console when getting/setting config values

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#3406]
We recently hooked up get/set of config values from the console. They seem to happen almost instantly.

However, when doing the same from CLI there's a noticeable delay in each command.

```sh
ftl config set --inline echo.default "coolnewvalue"
```

**Comment by alecthomas** [comment]
If this is in the ftl repo itself it's because the ftl command triggers a rebuild. The slowness is the build.

**Comment by wesbillman** [comment]
Would this be true without any changes to the ftl source? Like would we assume even a no-op build would be slow here? Basically, I was just issues this command over and over without making changes.
