### ISSUE TITLE
Modifying the dbname (mysql) fails.

### ISSUE THREAD

**Issue by bradleydwyer** [TBD54566975/ftl#3514]
Post a successful provisioning of a MySQL DB, if the db name is modified on a running system the new DB is not provisioned.

Modifying the db name back to the original does not cause the system to reestablish a working connection to the existing DB.

Steps (local dev):

1. Establish initial DB `func (MyDbConfig) Name() string { return "testdb" }`
2. Insert/Query works
3. Rename `func (MyDbConfig) Name() string { return "testdb2" }`
4. Insert/Query fails
5. Rename back `func (MyDbConfig) Name() string { return "testdb" }`
6. Insert/Query fails `call to verb mysql.query failed: failed to get database "testdb": database testdb does not match expected type of mysql`

**Comment by jvmakine** [comment]
@bradleydwyer I can not reproduce this in the latest main. Could you verify if it has been fixed in some of the recent refactorings?

**Comment by bradleydwyer** [comment]
I don't see this on latest either. Will close.
