### ISSUE TITLE
Filter panel should not scroll with event panel

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#389]
<img width="1470" alt="Screenshot 2023-09-16 at 7 29 48 am" src="https://github.com/TBD54566975/ftl/assets/41767/7762114c-493e-499c-ba91-5678fa84ffc1">

**Comment by wesbillman** [comment]
This is a good question. On other tools like DD it does scroll with the timeline. I think this might be due to the fact that the filter panel could require scrolling too if there are a bunch of filters. I think we can do either, but I built it this way intentionally :)
