### ISSUE TITLE
Console not live updating in staging after first module deployment

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#435]
I deployed the online-boutique, and the first module rolled out and was visible in the console, but subsequent modules wouldn't update the console without a full refresh.

One difference to ftl-dev, beyond the obvious, is that it has two controllers. There could be some issue where one controller is receiving the commands and the other isn't getting updates. Though that said, the CLI issues a whole bunch of requests, so I would expect 50% of them to hit each controller.

Strangely, `ftl call` events/logs do show up.

**Comment by wesbillman** [comment]
This is an interesting issue and I'm not 💯 on what the best approach is. That `Timeline` component sets the filters the first time to include all `modules` if none are currently selected in the filter. The idea here is that it will show all current modules by default when it runs. However, if modules are coming online at different times, I'm not sure what the filter should show. Ideally, it would be all modules if nothing has been selected.

We might have to add a flag like `user_has_changed_modules` or something so we know if we should include all modules or not during start up. Very open to other ideas here as well
