### ISSUE TITLE
Opening 3 tabs on the console causes it to hang

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#448]
Is there a concurrent connection limit/issue here? It seems like 3 tabs is the limit

@alecthomas do have any ideas on why this might happen

https://github.com/TBD54566975/ftl/assets/51647/b9ca6b9c-7431-4c96-82eb-f98600e8baa5

**Comment by alecthomas** [comment]
Browsers have a max connection limit per host, could that be it?

**Comment by alecthomas** [comment]
IIRC it's a websocket limit

**Comment by alecthomas** [comment]
I think the solution will be to cancel the streaming request when a tab loses focus and resume when it regains focus.
