### ISSUE TITLE
`ftl schema generate` hangs randomly

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#504]
To reproduce...

UPDATE: It seems like the generate command might just be failing to generate changes made to the go files. Still trying to reproduce

The only way I can get FTL to start running again is to wipe the DB

OLD STUFF:
> 
> 1. Add ingress to `ad.go`
>     ```go
>     //ftl:verb
>     //ftl:ingress GET /ad
>     func Get(ctx context.Context, req AdRequest) (AdResponse, error) {
>     ```
> 2. Add ingress to `cart.go` and make the path match
>     ```go
>     //ftl:verb
>     //ftl:ingress POST /ad
>     func AddItem(ctx context.Context, req AddItemRequest) (AddItemResponse, error) {
>     ```
> 
> Notice that `PullSchema` stops having new responses. I was personally testing this with the `ftl schema generate` command.

**Comment by alecthomas** [comment]
I haven't made any changes that would fix this.
