### ISSUE TITLE
Investigate getting rid of otlpmetricgrpc exporter

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#54]
It pulls in an obscene number of dependencies.

I think it would be a matter of copying [this](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlpmetric/otlpmetricgrpc/client.go) code and switching it to use Connect, and/or switching to otlpmetrichttp. The complication is we are implementing the gRPC OTLP server internally, so we probably need to do the former.

**Comment by wesbillman** [comment]
There are other parts of OTEL that use GRPC so this doesn't help ... at all.
