### ISSUE TITLE
Need optional support on FTL Schema

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#542]
We definitely need this so that we can define optional fields in our request/response data types. (and likely other places)

**Comment by KendallWeihe** [comment]
This also implies empty requests, but just calling it out explicitly!

Sadly, Kotlin doesn't support empty `data class`'s so right now I'm having to do...

```kotlin
data class GetOfferingsRequest(val nothing: String)
```

Maybe we need to expose a custom type from the FTL Kotlin runtime package for empty request/response types.

Although, should it be _empty_ or should it be _null_ 🤔 🤔 🤔
