### ISSUE TITLE
Kotlin exceptions cause `ftl call`s to return `unknown`

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#555]
Testing with the `ad-kotlin` module, I tried getting ads with an unknown key, which will hit this code:

```kotlin
  private fun contextualAds(contextKeys: List<String>): List<Ad> {
    return contextKeys.map { database[it] ?: throw Exception("no ad registered for this context key") }
  }
```

When the exception occurs, the return value is `unknown`.

![Screenshot 2023-11-04 at 8 31 48 AM](https://github.com/TBD54566975/ftl/assets/51647/c88733e5-b449-4bd7-80c6-7b2f5c3e9ba1)

```bash
ftl call ad.get '{"contextKeys": ["fake"]}'

error: Unary RPC failed: unknown: /xyz.block.ftl.v1.VerbService/Call
ftl: error: unknown
```

Would be nice if this `no ad registered for this context key` made it back to the caller.

**Comment by alecthomas** [comment]
I think this is related to #298 - for that one, exceptions/panics aren't being captured by the FTL runtime and converted into correct gRPC errors and/or log entries. I thought we had a similar issue for Kotlin too, but I can't find it.

**Comment by alecthomas** [comment]
@worstell this one's fixed now I think?
