### ISSUE TITLE
Kotlin response type support for `Map`

### ISSUE THREAD

**Issue by KendallWeihe** [TBD54566975/ftl#595]
We added support to do `typealias EchoResponse = Unit`, but could we also add support for `Map`?

----

```shell
mkdir proof; cd proof; ftl init kotlin . alice
```

Then edit `Alice.kt` to be this

```kotlin
package ftl.alice

import xyz.block.ftl.Context
import xyz.block.ftl.Ingress
import xyz.block.ftl.Method
import xyz.block.ftl.Verb

data class AliceRequest(val name: String)
typealias AliceResponse = Map<String, List<String>>

class Alice {
  @Verb
  fun echo(context: Context, req: AliceRequest): AliceResponse {
    println("Hello, ${req.name}!")
    return mapOf(
        "Category1" to listOf("Item1", "Item2", "Item3"),
        "Category2" to listOf("Item4", "Item5"),
        "Category3" to listOf("Item6")
    )
  }
}
```

Then do a 

```shell
mvn compile
```

And you'll see the build output 

```
...
[ERROR] Failed to execute goal com.github.ozsie:detekt-maven-plugin:1.23.3:check-with-type-resolution (default) on project ftl-module-alice: Execution default of goal com.github.ozsie:detekt-maven-plugin:1.23.3:check-with-type-resolution failed: Analyzing /Users/kendallw/Development/workspace/ftl/examples/proof/proof/ftl-module-alice/src/main/kotlin/ftl/alice/Alice.kt led to an exception.
[ERROR] Location: xyz.block.ftl.schemaextractor.SchemaExtractor.<init>(ExtractSchemaRule.kt:147)
[ERROR] The original exception message was: Return type of echo must be a data class or typealias of Unit
[ERROR] Running detekt '1.23.1' on Java '17.0.6+7-b469.82' on OS 'Mac OS X'
[ERROR] If the exception message does not help, please feel free to create an issue on our GitHub page.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :ftl-module-alice
```

**Comment by worstell** [comment]
I don't think we want to support this — the `typealias` thing is essentially a workaround to the requirement that Kotlin data classes must have members. By looking for this specific combination in our schema extraction, we can detect when the user would like an empty class in their schema.

The FTL spec is somewhat opinionated to encourage architectural best-practices. One of its requirements is that verbs accept/return explicitly defined (and named) request/response classes. Per @alecthomas's prior comment:
> Architecturally, it's very beneficial to have type separation between the different layers of your system. This allows them to be tailored for the specific requirements of each layer, and to evolve independently without refactoring impacting each other.

If instead of using `typealias AliceResponse = Map<String, List<String>>`, the response wraps a map as a member: `data class AliceResponse (val things: Map<String, List<String>>)`, you are free to extend it as needed.

**Comment by alecthomas** [comment]
Unfortunately this would make forward/backwards compatible changes impossible. For example if you started with:

```kotlin
typealias MyResponse = Map<String, String>
```

But then wanted to add concrete fields:

```kotlin
data class MyResponse(
  bag: Map<String, String>,
  id: Int,
)
```

This would be a backwards breaking change. Effectively you would be locked into this response type being a map forever.

**Comment by alecthomas** [comment]
Oops, didn't see Lizzy's response. Basically, what she said :)

**Comment by KendallWeihe** [comment]
Thanks for the explainers!
