### ISSUE TITLE
`ftl devel [<dir> ...]` will recursively find all `ftl.toml` files under a directory and start hot reloading them.

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#620]
We might want to add a `watch = [...]` field to the `ftl.toml` file to control which files trigger a reload, with defaults for each language. This should be a list of globs. Use https://github.com/bmatcuk/doublestar/v4 because it has a function for extracting the prefix. eg. given `src/main/kotlin/**/*.kt` you can get `src/main/kotlin` out.

We're getting a lot of language-specific config spread over a bunch of commands, so it might be an idea to create an abstraction here.

The algorithm will be something like:

1. Recursively find all the `ftl.toml` files, terminating recursion on that branch when one is found (modules can't be nested).
2. For each module, repeatedly recurse into each entry of `watch`, looking for changes.
3. For each file found put it into a map of path -> mod_time (from `os.ReadDir()`, each entry has an `Info().ModTime`). Then compare the old map to the new one: if the size of the map has changed, trigger, or if not, recurse and compare mod times and/or that entries exist in both. Deal with deletes and adds.

Have a look at scaffolder.walkDir() for an example.

**Comment by wesbillman** [comment]
Fixed with #630
