### ISSUE TITLE
warn if Go binaries/JAR dependency versions are out-of-sync

### ISSUE THREAD

**Issue by worstell** [TBD54566975/ftl#651]
We may want to explore ways of warning the user/prompting them to upgrade if their FTL Go binary and JAR versions are misaligned

**Comment by alecthomas** [comment]
Is this a dupe of #625, or something different?

**Comment by worstell** [comment]
> Is this a dupe of #625, or something different?

ooh yeah they're probably the same - are you thinking something like `ftl deploy` checks the cluster version for misalignment with the ftl.version declared by the module POM before deploying?

**Comment by alecthomas** [comment]
I think this issue will be solved by a combination of #670 and #669 .
