### ISSUE TITLE
ftl init kotlin removing `repositories` block

### ISSUE THREAD

**Issue by KendallWeihe** [TBD54566975/ftl#665]
Originally discovered [here](https://github.com/tbdeng/didpay-ftl/pull/59/commits/beccde86b3451db056c00dd25f76712944490052#diff-34049c3bc6deee4bbf269544338e0450399140da63fec684096d1ae0ce70b4bb) 

---

### Steps to recreate

1. `ftl init kotlin proof alice`
2. `cd proof`
3. Edit `pom.xml` and add the `<repositories>` block (pasted below)
4. `ftl init kotlin . bob`

```xml
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>danubetech</id>
            <url>https://repo.danubetech.com/repository/maven-public/</url>
        </repository>
    </repositories>
```

Notice how after step 4, the `<repositories>` block has been deleted

----

May be the same root issue as https://github.com/TBD54566975/ftl/issues/664

**Comment by worstell** [comment]
I wasn't able to reproduce this one locally. Were you running FTL on the latest version?

**Comment by KendallWeihe** [comment]
not an issue, was running an out of date cli

**Comment by KendallWeihe** [comment]
https://github.com/tbdeng/didpay-ftl/pull/60
