### ISSUE TITLE
`schema.ParseString` has errors when `DataRef`s are used

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#689]
Given this test string 
```
module todo {
	data AnotherType {}
	data CreateListRequest {
		another AnotherType
	}
	data CreateListResponse {}

	// Create a new list
	verb createList(todo.CreateListRequest) CreateListResponse
		calls createList
}
```

`sch, err := schema.ParseString("", testSchema)` will fail with the error `5:15: reference to unknown Verb "AnotherType"` in the `testParsing` function

**Comment by alecthomas** [comment]
I think we determined this was not a bug?
