### ISSUE TITLE
[ftl console] table fields mushing together

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/ftl#734]
check out the destination and request columns in the screenshot.

<img width="1719" alt="image" src="https://github.com/TBD54566975/ftl/assets/4887440/ba7a11cb-5b03-44e0-b458-c44ab31aa6a0">

will tackle this in a PR soon!

**Comment by alecthomas** [comment]
@mistermoe if you self-assigned because you want to take a crack at it, ignore that reassignment :)
