### ISSUE TITLE
Consider making `HttpResponse` constructor `headers` argument optional

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/ftl#772]
I think often times an `@HttpIngress` `@Verb` won't have any headers it wants to respond with. 

Also might be worth having FTL handle setting conventional http response headers, Implementing this in such away that allows developers to explicitly unset a response header FTL sends by default may be a bit tricky to get right in a way that doesn't seem awkward

**Comment by alecthomas** [comment]
I did have the same thought! Want to pair on it?

The Go server automatically sets some, what others were you thinking of? I think the logic could be that if you don't set any headers, FTL will set them, but if you send any headers FTL will do nothing.

**Comment by mistermoe** [comment]
@alecthomas yeah would love to pair! was poking around the ftl code and was thinking that [here](https://github.com/TBD54566975/ftl/blob/main/backend/controller/controller.go#L251-L255) is where the headers returned from an `@HttpIngress` `@Verb` were mapped back to the originating request. 

Thought that adding a function to [ingress](https://github.com/TBD54566975/ftl/blob/main/backend/controller/ingress/ingress.go) that returned a list of default headers may make sense?

**Comment by mistermoe** [comment]
oh and then potentially any changes needed to the kotlin runtime `HttpResponse` data class though that may not be necessary because it likely being autogenerated if i remember what @wesbillman was saying earlier today correctly

**Comment by alecthomas** [comment]
Yeah if you search for "Builtins" you'll find the schema definition, just add a ? to make it optional
