### ISSUE TITLE
JAR publishing is broken

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#817]
https://github.com/TBD54566975/ftl/actions/runs/7578470555/job/20641121612

**Comment by worstell** [comment]
i think this was just flakiness, the error indicated connectivity issues and eventually publishing resumed working

but this reminds me about the stuff we'd talked about a bit ago to make the process a little more robust - rolling back JAR publishing/Go releases if either counterpart were unsuccessful. i'll make a ticket to track this
