### ISSUE TITLE
FTL annotations with spaces fail silently

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#846]
When developing a module/verb, if the user uses `// ftl:verb` the module will be deployed but the verb will not be present in the schema.

Should we handle this in a way that lets the user know there was an issue?

**Comment by alecthomas** [comment]
Maybe we should lint this, but FTR the syntax of `//<key>:<value>` is called a [comment directive](https://tip.golang.org/doc/comment) in Go and is a separate field in the AST. This failed because we only inspect the directives, not the comments themselves.

**Comment by alecthomas** [comment]
I think this is just a Go knowledge gap issue.
