### ISSUE TITLE
Lower case response fields don't show in response and don't warn or error

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#848]
If a verb has a response struct like
```go
type SIOPV2AuthRequest struct {
	scope string
}
```

The http response will not have `scope` and it's pretty difficult to debug

**Comment by alecthomas** [comment]
This is normal Go behaviour but we could warn/error about it, because FTL can't do anything with these fields.

**Comment by alecthomas** [comment]
This should error.
