### ISSUE TITLE
Make `ftl deploy` deploy all modules in a folder and then complete after

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#854]
Ideally we can leverage this behavior from the `ftl dev` command as well. Would could have `ftl dev` be responsible for watching things and `ftl deploy` be responsible for building everything.

`ftl deploy .` would deploy all modules (and keep retrying failures) until everything deploys successfully, then would return.

This will be useful for testing in the future. We can serve and deploy all modules, then run tests agains them.

**Comment by worstell** [comment]
included [here](https://github.com/TBD54566975/ftl/issues/960)
