### ISSUE TITLE
Support `Bytes` as request and response payload.

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#856]

**Comment by alecthomas** [comment]
cc @tomdaffurn

**Comment by wesbillman** [comment]
@alecthomas do you think we should support other types as well? Or just `[]bytes` or a `DataRef`?

I think to support things like `builtin.HttpRequest/Response[string]` we'll need a way to convert `r.Body` to `schema.String` etc. for all the schema types.

**Comment by alecthomas** [comment]
I was thinking just start with these two as that unlocks almost everything else, albeit manually, then we can think about if/how to support other types?
