### ISSUE TITLE
Request/response `(Type, Content-Type)` specification

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#876]
### Request/response type, Content-Type, and semantics

- [x] `Bytes` / `*` / Raw bytes will be passed through as-is for any content-type.
- [x] `String` / ` text/*` /  Passed through as-is.
- [x] `Data` / `application/json` / Data structures will be decoded/encoded as JSON.
- [x] `Array` / `application/json` / Arrays will be decoded/encoded as JSON. (#915)
- [x] `Unit` / None / Unit does not expect or set a response type, and will default to 204 No Content for responses.
- [x] `Int`|`Float`|`Bool` / `text/plain` / Return these types as string literals? (#905)
- [x] Add `data builtin.Empty {}` so that users can do `builtin.HttpResponse[builtin.Empty]` and get an empty JSON object `{}`?

---

Also, refactor this to make more sense with raw strings

https://github.com/TBD54566975/ftl/blob/main/integration/testdata/go/httpingress/echo.go#L95-L101

**Comment by alecthomas** [comment]
I think that we should enumerate all the different response types (data, array, string, bytes, etc.) and what content-types are supported for each, and what they mean. Then implement them. We can just do it in this issue description as a checklist, then implement them.
