### ISSUE TITLE
"Failed to increase deployment replicas" should be logged at error

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#899]
This should really be logged at error, but _only_ if we've already tried to increase replicas and it's failed once.

The other log messages are fine to be at Debug I think.

_Originally posted by @alecthomas in https://github.com/TBD54566975/ftl/pull/890#discussion_r1481940651_

**Comment by matt2e** [comment]
Closing after discussing with @alecthomas, debug is fine for now
