### ISSUE TITLE
Consider switching "alias" annotation to "json"

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#908]
The rationale is twofold:

1. It is almost certain that if a type is to be shared across multiple ingress methods, such as HTTP, gRPC, and GraphQL, users will want to be able to use different aliases for different protocols. The choice of `alias` doesn't allow for that.
2. It will simplify interacting with HTTP ingress endpoints from Go code such as integration tests, because their will only need to be a single annotation, `json:"xyz"`.

Schema should change to:

```
data Foo {
  field String alias http bar
}

verb bar() 
  ingress http GET /bar
```

Go annotations should change to:

```
json:"bar"
```

Kotlin annotation should change to something like this, but dig into whether we should just use `@JsonProperty`? Is this part of JAX-RS or some random thing from Jackson?

```
@JsonProperty("bar")
```

Edit: there doesn't seem to be any standard at all. Gson uses `SerializedName`, Jackson uses `@JsonProperty` - let's just use `@Json`.

**Comment by wesbillman** [comment]
Yeah after a bit of googling and chatting with my friend Chad, it seems like there's no standard for this. There are standards for serializing, but they leave out the part about this being for `JSON` on http. So `@Json` sounds good to me as well 👍
