### ISSUE TITLE
include transitive dependencies in buildengine.Module dependencies

### ISSUE THREAD

**Issue by worstell** [TBD54566975/ftl#981]
this doesn't appear to be the case presently

we should also probably always be including `builtins` as a dependency?

**Comment by alecthomas** [comment]
Agreed on the second point, but I think the transitive deps will be covered because we'll have to load the direct dependencies, and they will include the next level of deps, and so on.

**Comment by worstell** [comment]
ahh - ok i think `buildengine.Module dependencies` isn't the right place then. the issue i encountered was with external module generation - the logic to generate external dependencies for kotlin filters the schema for dependencies and only generates those. 

in a scenario where module A depends on module B, and module B depends on module C: 
A -> B -> C

building module A will only generate an external module for B. but in this case we also need to generate C in order for A to compile, because the generated module for B may include types from C that will cause build failures C isn't generated too. 

i'll take a look at the kotlin logic in the context of your new build engine changes to fix

**Comment by alecthomas** [comment]
`buildengine.Engine.Graph()` can be passed a set of modules and (if it's working correctly) it should return the full transitive dependencies.
